/*
 * ContractMarketDialog.java
 *
 * Copyright (c) 2014-2024 Carl Spain. All rights reserved.
 *
 * This file is part of MekHQ.
 *
 * MekHQ is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MekHQ is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with MekHQ. If not, see <http://www.gnu.org/licenses/>.
 */
package mekhq.gui.dialog;

import megamek.client.ui.preferences.*;
import megamek.client.ui.swing.util.UIUtil;
import megamek.common.util.sorter.NaturalOrderComparator;
import megamek.logging.MMLogger;
import mekhq.MekHQ;
import mekhq.campaign.Campaign;
import mekhq.campaign.JumpPath;
import mekhq.campaign.finances.enums.TransactionType;
import mekhq.campaign.market.contractMarket.AbstractContractMarket;
import mekhq.campaign.mission.AtBContract;
import mekhq.campaign.mission.Contract;
import mekhq.campaign.universe.Factions;
import mekhq.gui.FactionComboBox;
import mekhq.gui.sorter.FormattedNumberSorter;
import mekhq.gui.sorter.IntegerStringSorter;
import mekhq.gui.utilities.JScrollPaneWithSpeed;
import mekhq.gui.view.ContractSummaryPanel;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import java.util.*;

import static mekhq.campaign.mission.resupplyAndCaches.Resupply.triggerConvoyDialog;
import static mekhq.campaign.universe.Factions.getFactionLogo;

/**
 * Presents contract offers generated by ContractMarket
 * <p>
 * Code borrowed heavily from PersonnelMarketDialog
 *
 * @author Neoancient
 */
public class ContractMarketDialog extends JDialog {
    private static final MMLogger logger = MMLogger.create(ContractMarketDialog.class);

    /* Save these settings between instantiations */
    private static boolean payMRBC = true;
    private static int advance = 25;
    private static int signingBonus = 0;
    private static int sharePct = 20;

    private Campaign campaign;
    private AbstractContractMarket contractMarket;
    private Contract selectedContract = null;
    private List<String> possibleRetainerContracts;

    private JScrollPane scrollContractView;
    private ContractSummaryPanel contractView;

    private JCheckBox chkMRBC;
    private JSpinner spnSigningBonus;
    private JSpinner spnAdvance;
    private JSpinner spnSharePct;
    private JTable tableContracts;
    private JLabel lblCurrentRetainer;
    private JLabel lblRetainerEmployer;
    private JButton btnEndRetainer;
    private JLabel lblRetainerAvailable;
    private FactionComboBox cbRetainerEmployer;
    private JButton btnStartRetainer;

    final static ResourceBundle resourceMap = ResourceBundle.getBundle("mekhq.resources.ContractMarketDialog",
        MekHQ.getMHQOptions().getLocale());

    public ContractMarketDialog(final JFrame frame, final Campaign campaign) {
        super(frame, true);
        this.campaign = campaign;
        contractMarket = campaign.getContractMarket();
        possibleRetainerContracts = new ArrayList<>();
        if (campaign.getFaction().isMercenary()) {
            countSuccessfulContracts();
        }
        initComponents();
        setLocationRelativeTo(frame);
        setUserPreferences();
    }

    /*
     * A balance of six or more successful contracts with the same
     * employer results in the offer of a retainer contract.
     */
    private void countSuccessfulContracts() {
        HashMap<String, Integer> successfulContracts = new HashMap<>();
        for (AtBContract contract : campaign.getCompletedAtBContracts()) {
            if (contract.getEmployerCode().equals(campaign.getRetainerEmployerCode())) {
                continue;
            }
            int num = successfulContracts.getOrDefault(contract.getEmployerCode(), 0);
            successfulContracts.put(contract.getEmployerCode(),
                    num + (contract.getStatus().isSuccess() ? 1 : -1));
        }
        for (String key : successfulContracts.keySet()) {
            if (successfulContracts.get(key) >= 6) {
                possibleRetainerContracts.add(key);
            }
        }
    }

    private void initComponents() {
        JScrollPane scrollTableContracts = new JScrollPaneWithSpeed();
        scrollContractView = new JScrollPaneWithSpeed();
        JPanel panelTable = new JPanel();
        JPanel panelFees = new JPanel();
        JPanel panelRetainer = new JPanel();
        JPanel panelOKBtns = new JPanel();
        contractView = null;
        JButton btnGenerate = new JButton();
        JButton btnRemove = new JButton();
        JButton btnAccept = new JButton();
        JButton btnClose = new JButton();

        chkMRBC = new JCheckBox();
        chkMRBC.addItemListener(evt -> {
            payMRBC = chkMRBC.isSelected();
            for (Contract c : contractMarket.getContracts()) {
                c.setMRBCFee(payMRBC);
                c.calculateContract(campaign);
            }
            if (contractView != null) {
                contractView.refreshAmounts();
            }
        });
        JLabel lblAdvance = new JLabel();
        spnAdvance = new JSpinner(new SpinnerNumberModel(advance, 0, 25, 5));
        spnAdvance.addChangeListener(evt -> {
            advance = (Integer) spnAdvance.getValue();
            for (Contract c : contractMarket.getContracts()) {
                c.setAdvancePct(advance);
                c.calculateContract(campaign);
            }
            if (contractView != null) {
                contractView.refreshAmounts();
            }
        });
        JLabel lblSigningBonus = new JLabel();
        spnSigningBonus = new JSpinner(new SpinnerNumberModel(signingBonus, 0, 10, 1));
        spnSigningBonus.addChangeListener(evt -> {
            signingBonus = (Integer) spnSigningBonus.getValue();
            for (Contract c : contractMarket.getContracts()) {
                c.setSigningBonusPct(signingBonus);
                c.calculateContract(campaign);
            }
            if (contractView != null) {
                contractView.refreshAmounts();
            }
        });

        JLabel lblSharePct = new JLabel();
        spnSharePct = new JSpinner(new SpinnerNumberModel(sharePct, 20, 50, 10));
        spnSharePct.addChangeListener(evt -> {
            sharePct = (Integer) spnSharePct.getValue();
            for (Contract c : contractMarket.getContracts()) {
                if (campaign.getCampaignOptions().isUseAtB()
                        && campaign.getCampaignOptions().isUseShareSystem()
                        && c instanceof AtBContract) {
                    ((AtBContract) c).setAtBSharesPercent(sharePct);
                    c.calculateContract(campaign);
                }
            }
            if (contractView != null) {
                contractView.refreshAmounts();
            }
        });

        lblCurrentRetainer = new JLabel();
        lblRetainerEmployer = new JLabel();
        btnEndRetainer = new JButton();
        lblRetainerAvailable = new JLabel();
        cbRetainerEmployer = new FactionComboBox();
        btnStartRetainer = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(resourceMap.getString("Form.title"));
        setName("Form");
        getContentPane().setLayout(new BorderLayout());

        scrollTableContracts.setMinimumSize(new Dimension(500, 400));
        scrollTableContracts.setName("scrollTableContracts");
        scrollTableContracts.setPreferredSize(new Dimension(500, 400));

        chkMRBC.setName("chkMRBC");
        chkMRBC.setText(resourceMap.getString("checkMRBC.text"));
        chkMRBC.setSelected(payMRBC);
        panelFees.add(chkMRBC);

        lblAdvance.setText(resourceMap.getString("lblAdvance.text"));
        panelFees.add(lblAdvance);
        panelFees.add(spnAdvance);
        lblSigningBonus.setText(resourceMap.getString("lblSigningBonus.text"));
        panelFees.add(lblSigningBonus);
        panelFees.add(spnSigningBonus);
        lblSharePct.setText(resourceMap.getString("lblSharePct.text"));
        if (campaign.getCampaignOptions().isUseShareSystem()) {
            panelFees.add(lblSharePct);
            panelFees.add(spnSharePct);
        }

        Vector<Vector<String>> data = new Vector<>();
        for (Contract c : contractMarket.getContracts()) {
            // Changes in rating or force size since creation can alter some details
            if (c instanceof AtBContract atbContract) {
                atbContract.initContractDetails(campaign);
                campaign.getContractMarket().calculatePaymentMultiplier(campaign, atbContract);
                atbContract.setPartsAvailabilityLevel(atbContract.getContractType().calculatePartsAvailabilityLevel());
                atbContract.setAtBSharesPercent(campaign.getCampaignOptions().isUseShareSystem()
                        ? (Integer) spnSharePct.getValue()
                        : 0);
            }
            c.setStartDate(null);
            c.setMRBCFee(payMRBC);
            c.setAdvancePct(advance);
            c.setSigningBonusPct(signingBonus);
            c.calculateContract(campaign);

            Vector<String> row = new Vector<>();
            if (c instanceof AtBContract) {
                row.add(((AtBContract) c).getEmployerName(campaign.getGameYear()));
                row.add(((AtBContract) c).getEnemyName(campaign.getGameYear()));
                if (((AtBContract) c).isSubcontract()) {
                    row.add(((AtBContract) c).getContractType() + " (Subcontract)");
                } else {
                    row.add(((AtBContract) c).getContractType().toString());
                }
            } else {
                row.add(c.getEmployer());
                row.add("");
                row.add(c.getType());
            }

            final JumpPath path = campaign.calculateJumpPath(campaign.getCurrentSystem(), c.getSystem());
            final int days = (int) Math.ceil(path.getTotalTime(c.getStartDate(),
                    campaign.getLocation().getTransitTime()));
            row.add(Integer.toString(days));
            row.add(c.getEstimatedTotalProfit(campaign).toAmountAndSymbolString());
            data.add(row);
        }

        Vector<String> colNames = new Vector<>();
        colNames.add("Employer");
        colNames.add("Enemy");
        colNames.add("Mission Type");
        colNames.add("Transit Time");
        colNames.add("Estimated Profit");

        tableContracts = new JTable();
        DefaultTableModel tblContractsModel = new DefaultTableModel(data, colNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableContracts.setModel(tblContractsModel);
        tableContracts.setName("tableContracts");
        tableContracts.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableContracts.createDefaultColumnsFromModel();
        tableContracts.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        tableContracts.getSelectionModel().addListSelectionListener(evt -> {
            if (!evt.getValueIsAdjusting()) {
                contractChanged();
            }
        });

        tableContracts.setIntercellSpacing(new Dimension(0, 0));
        tableContracts.setShowGrid(false);
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(tblContractsModel);
        sorter.setComparator(0, new NaturalOrderComparator());
        sorter.setComparator(1, new NaturalOrderComparator());
        sorter.setComparator(2, new NaturalOrderComparator());
        sorter.setComparator(3, new IntegerStringSorter());
        sorter.setComparator(4, new FormattedNumberSorter());
        tableContracts.setRowSorter(sorter);
        scrollTableContracts.setViewportView(tableContracts);

        scrollContractView.setMinimumSize(new Dimension(500, 600));
        scrollContractView.setPreferredSize(new Dimension(500, 600));
        scrollContractView.setViewportView(null);

        panelTable.setLayout(new BorderLayout());
        panelTable.add(panelFees, BorderLayout.PAGE_START);
        panelTable.add(scrollTableContracts, BorderLayout.CENTER);
        panelTable.add(panelRetainer, BorderLayout.PAGE_END);

        panelRetainer.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();

        lblCurrentRetainer.setText(resourceMap.getString("lblCurrentRetainer.text"));
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.NORTHWEST;
        gbc.fill = GridBagConstraints.NONE;
        panelRetainer.add(lblCurrentRetainer, gbc);
        if (null != campaign.getRetainerEmployerCode()) {
            lblRetainerEmployer.setText(Factions.getInstance().getFaction(campaign.getRetainerEmployerCode())
                    .getFullName(campaign.getGameYear()));
        }
        gbc.gridx = 1;
        gbc.gridy = 0;
        panelRetainer.add(lblRetainerEmployer, gbc);
        btnEndRetainer.setText(resourceMap.getString("btnEndRetainer.text"));
        gbc.gridx = 0;
        gbc.gridy = 1;
        panelRetainer.add(btnEndRetainer, gbc);
        lblCurrentRetainer.setVisible(null != campaign.getRetainerEmployerCode());
        lblRetainerEmployer.setVisible(null != campaign.getRetainerEmployerCode());
        btnEndRetainer.setVisible(null != campaign.getRetainerEmployerCode());
        btnEndRetainer.addActionListener(ev -> {
            campaign.setRetainerEmployerCode(null);
            campaign.setRetainerStartDate(null);
            lblCurrentRetainer.setVisible(false);
            lblRetainerEmployer.setVisible(false);
            btnEndRetainer.setVisible(false);
            // Add faction back to available ones
            countSuccessfulContracts();
            lblRetainerAvailable.setVisible(!possibleRetainerContracts.isEmpty());
            cbRetainerEmployer.setVisible(!possibleRetainerContracts.isEmpty());
            btnStartRetainer.setVisible(!possibleRetainerContracts.isEmpty());
        });

        lblRetainerAvailable.setText(resourceMap.getString("lblRetainerAvailable.text"));
        gbc.gridx = 0;
        gbc.gridy = 2;
        panelRetainer.add(lblRetainerAvailable, gbc);
        cbRetainerEmployer.addFactionEntries(possibleRetainerContracts, campaign.getGameYear());
        gbc.gridx = 1;
        gbc.gridy = 2;
        panelRetainer.add(cbRetainerEmployer, gbc);
        btnStartRetainer.setText(resourceMap.getString("btnStartRetainer.text"));
        gbc.gridx = 0;
        gbc.gridy = 3;
        panelRetainer.add(btnStartRetainer, gbc);
        lblRetainerAvailable.setVisible(!possibleRetainerContracts.isEmpty());
        cbRetainerEmployer.setVisible(!possibleRetainerContracts.isEmpty());
        btnStartRetainer.setVisible(!possibleRetainerContracts.isEmpty());
        btnStartRetainer.addActionListener(e -> {
            campaign.setRetainerEmployerCode(cbRetainerEmployer.getSelectedItemKey());
            lblCurrentRetainer.setVisible(true);
            lblRetainerEmployer.setVisible(true);
            btnEndRetainer.setVisible(true);
            lblRetainerEmployer.setText(Factions.getInstance().getFaction(campaign.getRetainerEmployerCode())
                    .getFullName(campaign.getGameYear()));
            // Remove the selected faction and add the previous one, if any
            countSuccessfulContracts();
            lblRetainerAvailable.setVisible(!possibleRetainerContracts.isEmpty());
            cbRetainerEmployer.setVisible(!possibleRetainerContracts.isEmpty());
            btnStartRetainer.setVisible(!possibleRetainerContracts.isEmpty());
        });

        JSplitPane splitMain = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, panelTable, scrollContractView);
        splitMain.setOneTouchExpandable(true);
        splitMain.setResizeWeight(0.0);
        getContentPane().add(splitMain, BorderLayout.CENTER);

        panelOKBtns.setLayout(new GridBagLayout());

        btnGenerate.setText(resourceMap.getString("btnGenerate.text"));
        btnGenerate.setName("btnGenerate");
        btnGenerate.addActionListener(evt -> {
            AtBContract c = contractMarket.addAtBContract(campaign);

            if (c == null) {
                campaign.addReport(resourceMap.getString("report.UnableToGMContract"));
                return;
            }

            c.initContractDetails(campaign);
            c.setPartsAvailabilityLevel(c.getContractType().calculatePartsAvailabilityLevel());
            c.setAtBSharesPercent(campaign.getCampaignOptions().isUseShareSystem()
                    ? (Integer) spnSharePct.getValue()
                    : 0);
            c.setStartDate(null);
            c.setMRBCFee(payMRBC);
            c.setAdvancePct(advance);
            c.setSigningBonusPct(signingBonus);

            c.calculateContract(campaign);
            Vector<String> row = new Vector<>();
            row.add(c.getEmployerName(campaign.getGameYear()));
            row.add(c.getEnemyName(campaign.getGameYear()));
            row.add(c.getContractType().toString());
            final JumpPath path = campaign.calculateJumpPath(campaign.getCurrentSystem(), c.getSystem());
            final int days = (int) Math.ceil(path.getTotalTime(c.getStartDate(),
                    campaign.getLocation().getTransitTime()));
            row.add(Integer.toString(days));
            row.add(c.getEstimatedTotalProfit(campaign).toAmountAndSymbolString());
            ((DefaultTableModel) tableContracts.getModel()).addRow(row);
        });
        btnGenerate.setEnabled(campaign.isGM());
        panelOKBtns.add(btnGenerate, new GridBagConstraints());

        btnRemove.setText(resourceMap.getString("btnRemove.text"));
        btnRemove.setName("btnRemove");
        btnRemove.addActionListener(evt -> {
            if (selectedContract == null) {
                return;
            }
            contractMarket.removeContract(selectedContract);
            ((DefaultTableModel) tableContracts.getModel())
                    .removeRow(tableContracts.convertRowIndexToModel(tableContracts.getSelectedRow()));
        });
        panelOKBtns.add(btnRemove, new GridBagConstraints());

        btnAccept.setText(resourceMap.getString("btnAccept.text"));
        btnAccept.setName("btnAccept");
        btnAccept.addActionListener(this::acceptContract);
        panelOKBtns.add(btnAccept, new GridBagConstraints());

        btnClose.setText(resourceMap.getString("btnClose.text"));
        btnClose.setName("btnClose");
        btnClose.addActionListener(this::btnCloseActionPerformed);
        panelOKBtns.add(btnClose, new GridBagConstraints());

        getContentPane().add(panelOKBtns, BorderLayout.PAGE_END);

        pack();
    }

    @Deprecated // These need to be migrated to the Suite Constants / Suite Options Setup
    private void setUserPreferences() {
        try {
            PreferencesNode preferences = MekHQ.getMHQPreferences().forClass(ContractMarketDialog.class);

            chkMRBC.setName("payMRBCFee");
            preferences.manage(new JToggleButtonPreference(chkMRBC));

            spnAdvance.setName("advancePercentage");
            preferences.manage(new JIntNumberSpinnerPreference(spnAdvance));

            spnSigningBonus.setName("signingBonusPercentage");
            preferences.manage(new JIntNumberSpinnerPreference(spnSigningBonus));

            spnSharePct.setName("sharePercentage");
            preferences.manage(new JIntNumberSpinnerPreference(spnSharePct));

            tableContracts.setName("contractsTable");
            preferences.manage(new JTablePreference(tableContracts));

            this.setName("dialog");
            preferences.manage(new JWindowPreference(this));
        } catch (Exception ex) {
            logger.error("Failed to set user preferences", ex);
        }
    }

    public Contract getContract() {
        return selectedContract;
    }

    private void acceptContract(ActionEvent evt) {
        if (selectedContract != null) {
            if (selectedContract instanceof AtBContract) {
                if (!triggerConfirmationDialog()) {
                    return;
                }

                if (selectedContract.getCommandRights().isIndependent()) {
                    if (selectedContract instanceof AtBContract) {
                        triggerConvoyDialog(campaign, (AtBContract) selectedContract);
                    }
                }
            }

            selectedContract.setName(contractView.getContractName());
            campaign.getFinances().credit(TransactionType.CONTRACT_PAYMENT, campaign.getLocalDate(),
                    selectedContract.getTotalAdvanceAmount(),
                    "Advance funds for " + selectedContract.getName());
            campaign.addMission(selectedContract);
            // must be invoked after campaign.addMission to ensure presence of mission ID
            selectedContract.acceptContract(campaign);
            contractMarket.removeContract(selectedContract);
            ((DefaultTableModel) tableContracts.getModel()).removeRow(tableContracts
                    .convertRowIndexToModel(tableContracts.getSelectedRow()));
            refreshContractView();
        }
    }

    /**
     * Displays a confirmation dialog with a message and options to accept or refuse the mission.
     *
     * @return {@code true} if the accept button is clicked, {@code false} if the refuse button is
     * clicked
     */
    private boolean triggerConfirmationDialog() {
        final boolean[] result = new boolean[] {true};

        int difficulty = ((AtBContract) selectedContract).calculateContractDifficulty(campaign);

        // Retrieves the title from the resources
        String title = resourceMap.getString("incomingTransmission.title");

        // An ImageIcon to hold the faction icon
        ImageIcon icon = getFactionLogo(campaign, ((AtBContract) selectedContract).getEmployerCode(),
            true);

        // Get the resource string
        String resourceKey = "";

        if (difficulty == -99) {
            resourceKey = "messageChallengeUnknown.text";
        } else if (difficulty <= 2) {
            resourceKey = "messageChallengeVeryEasy.text";
        } else if (difficulty > 8) {
            resourceKey = "messageChallengeVeryHard.text";
        } else if (difficulty > 6) {
            resourceKey = "messageChallengeHard.text";
        }

        // If resourceKey is not found, just return true, acting as if the player had accepted the mission
        if (resourceKey.isEmpty()) {
            return true;
        }

        String messageResource = resourceMap.getString(resourceKey);

        // Format the HTML message
        String message = String.format("<html><i><div style='width: %s; text-align:center;'>%s</div></i></html>",
            UIUtil.scaleForGUI(500),
            messageResource);

        // If no message for provided difficulty, act as if the player had accepted the mission.
        if (message.isBlank()) {
            return true;
        }

        // Create a text pane to display the message
        JTextPane textPane = new JTextPane();
        textPane.setContentType("text/html");
        textPane.setText(message);
        textPane.setEditable(false);

        // Create a panel to display the icon and the message
        JPanel panel = new JPanel(new BorderLayout());
        JLabel imageLabel = new JLabel(icon);
        panel.add(imageLabel, BorderLayout.CENTER);
        panel.add(textPane, BorderLayout.SOUTH);

        // Create a custom dialog
        JDialog dialog = new JDialog();
        dialog.setTitle(title);
        dialog.setLayout(new BorderLayout());

        // Create an accept button and add its action listener.
        // When clicked, it will set the result to true and close the dialog
        JButton acceptButton = new JButton(resourceMap.getString("responseAccept.text"));
        acceptButton.addActionListener(e -> {
            result[0] = true;
            dialog.dispose();
        });

        // Create a refuse button and add its action listener.
        // When clicked, it will trigger a refusal confirmation dialog
        String refusalOption = resourceMap.getString("responseReturn.text");
        JButton refuseButton = new JButton(refusalOption);
        refuseButton.addActionListener(e -> {
            result[0] = false;
            dialog.dispose();
        });

        // Attach a window listener
        dialog.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                result[0] = false;
                dialog.dispose();
            }
        });

        // Create a panel for buttons and add buttons to it
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(acceptButton);
        buttonPanel.add(refuseButton);

        // Add the original panel and button panel to the dialog
        dialog.add(panel, BorderLayout.CENTER);
        dialog.add(buttonPanel, BorderLayout.SOUTH);

        dialog.pack();  // Size the dialog to fit the preferred size and layouts of its components
        dialog.setLocationRelativeTo(null);  // Center the dialog on the screen
        dialog.setModal(true);  // Make the dialog block user input to other top-level windows
        dialog.setVisible(true);

        return result[0];
    }

    private void btnCloseActionPerformed(ActionEvent evt) {
        selectedContract = null;
        setVisible(false);
    }

    private void contractChanged() {
        int view = tableContracts.getSelectedRow();
        if (view < 0) {
            // selection got filtered away
            selectedContract = null;
            refreshContractView();
            return;
        }
        /* preserve the name given to the previous contract (if any) */
        if (selectedContract != null && contractView != null) {
            selectedContract.setName(contractView.getContractName());
        }

        selectedContract = contractMarket.getContracts().get(tableContracts.convertRowIndexToModel(view));
        refreshContractView();
    }

    void refreshContractView() {
        int row = tableContracts.getSelectedRow();
        if (row < 0) {
            contractView = null;
            scrollContractView.setViewportView(null);
            return;
        }
        contractView = new ContractSummaryPanel(selectedContract, campaign,
                campaign.getCampaignOptions().isUseAtB()
                        && selectedContract instanceof AtBContract
                        && !((AtBContract) selectedContract).isSubcontract());
        scrollContractView.setViewportView(contractView);
        // This odd code is to make sure that the scrollbar stays at the top
        // I can't just call it here, because it ends up getting reset somewhere later
        SwingUtilities.invokeLater(() -> scrollContractView.getVerticalScrollBar().setValue(0));
    }
}
