package mekhq.campaign.mission;

import java.util.ArrayList;
import java.util.List;

/**
 * This class contains parameters useful for maps generated by atb-stratcon maps
 * @author NickAragua
 *
 */
public class ScenarioMapParameters {
    // map properties:
    // base width/height range
    // map scaling increment (width/height)
    // allowed terrain types
    
    public int baseWidth;
    public int baseHeight;
    public int widthScalingIncrement;
    public int heightScalingIncrement;
    public List<Integer> allowedTerrainTypes = new ArrayList<>();
}
