# Copyright (C) 2005-2026 The MegaMek Team. All Rights Reserved.
#
# This file is part of MekHQ.
#
# MekHQ is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License (GPL),
# version 3 or (at your option) any later version,
# as published by the Free Software Foundation.
#
# MekHQ is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# A copy of the GPL should have been included with this project;
# if not, see <https://www.gnu.org/licenses/>.
#
# NOTICE: The MegaMek organization is a non-profit group of volunteers
# creating free software for the BattleTech community.
#
# MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
# of The Topps Company, Inc. All Rights Reserved.
#
# Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
# InMediaRes Productions, LLC.
#
# MechWarrior Copyright Microsoft Corporation. MegaMek was created under
# Microsoft's "Game Content Usage Rules"
# <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
# affiliated with Microsoft.
# suppress inspection "UnusedProperty" for the whole file
actionCheck.miscModifier=Misc Modifier
actionCheckResult.success={0}{1} <span color="{2}"><b>Passed</b></span> {3} <b>{4}</b> \
check with a roll of <b>{5}</b> vs. a target number of <b>{6}</b>.
actionCheckResult.failure={0}{1} <span color="{2}"><b>Failed</b></span> {3} <b>{4}</b> \
check with a roll of <b>{5}</b> vs. a target number of <b>{6}</b>.
actionCheckResult.naturalAptitude=Used Natural Aptitude.
actionCheckResult.rerolled=Used a point of <b>Edge</b>.
acquisition.modifier.automaticSuccess=Automatic Success
acquisition.modifier.clanTech=You cannot acquire clan parts
acquisition.modifier.ISTech=You cannot acquire inner sphere parts
acquisition.modifier.techLevel=You cannot acquire parts of this tech level
acquisition.modifier.notInvented=It has not been invented yet!
acquisition.modifier.extinct=It is extinct!
acquisition.modifier.waitForNewCycle=You must wait until the new cycle to check for this part. Further attempts \
will be added to the shopping list.
acquisition.modifier.noPersonnel=Your procurement personnel have used up all their acquisition attempts for this period
acquisition.modifier.missingRequiredSkill=No skill
acquisition.modifier.contractPartAvailability=Contract
acquisition.modifier.grayMonday=Gray Monday
acquisition.impossible=<font color="{0}"><b>{1} can''t search for {2} on {3} because:</b></font> {4}
acquisition.failure=<font color="{0}"><b>{1} is unable to find contacts for {2} on {3} at TN: {4}</b> \
- Modifiers (Tech: {5,choice,0#|0<+}{5}, Industry: {6,choice,0#|0<+}{6}, Outputs: {7,choice,0#|0<+}{7})</font>
acquisition.success=<font color="{0}"><b>{1} has found a contact for {2} on {3} at TN: {4}</b> \
- Modifiers (Tech: {5,choice,0#|0<+}{5}, Industry: {6,choice,0#|0<+}{6}, Outputs: {7,choice,0#|0<+}{7})</font>
