# Copyright (C) 2026 The MegaMek Team. All Rights Reserved.
#
# This file is part of MekHQ.
#
# MekHQ is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License (GPL),
# version 3 or (at your option) any later version,
# as published by the Free Software Foundation.
#
# MekHQ is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# A copy of the GPL should have been included with this project;
# if not, see <https://www.gnu.org/licenses/>.
#
# NOTICE: The MegaMek organization is a non-profit group of volunteers
# creating free software for the BattleTech community.
#
# MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
# of The Topps Company, Inc. All Rights Reserved.
#
# Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
# InMediaRes Productions, LLC.
#
# MechWarrior Copyright Microsoft Corporation. MegaMek was created under
# Microsoft's "Game Content Usage Rules"
# <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
# affiliated with Microsoft.
ChaosReputation.update={0}<b>Chaos Campaign Reputation</b>{1} has been updated for <b>{2}</b>. Reputation from \
  personnel was <b>{3}</b>. Your debt penalty was <b>{4}</b>. Your manual modifier was <b>{5}</b>. Your new \
  Reputation total is <b>{6}</b>.
ChaosReputation.contractSuccess={0}<b>Contract Success:</b>{1} Reputation has increased by {2}!
ChaosReputation.brokenContract={0}<b>Broken Contract:</b>{1} Reputation has been halved (to a minimum change of -{2});
ChaosReputation.piracy.booty=Booty from {0}
ChaosReputation.piracy.dialog.ic=Hey {0}, the crew tallied up the haul from our last raid, and it totals to {1} \
  C-Bills!\
  <p>{1}</p>
ChaosReputation.piracy.dialog.caught=Unfortunately, we''ve all been flagged for piracy.
ChaosReputation.piracy.dialog.notCaught=The best part? Nobody was able to track us!
ChaosReputation.piracy.dialog.ooc=You rolled {0} vs. {1} to avoid a Criminal Record penalty of {2}.
report.averageExperience=Average Experience
report.chaosReputation=Reputation
report.experienceLevel=Experience Level
report.personnel=Personnel
report.reputationValue=Reputation
report.totalExperience=Total Experience Points
report.rolesCounted=Roles Counted
report.averageSkillLevel=Average Experience Level
report.averageReputation=Average Reputation
report.debtPenalty=Debt Penalty
report.manualModifier=Manual Modifier
report.otherModifiers=Other Modifier
report.reputationTotal=Total Reputation
campaignLevel.tooltip=<html>The overall Chaos Campaign Reputation for your force, tracked at the campaign level.\
  <br>\
  <br><b>Reputation:</b> {0}\
  <br><b>Debt Penalty:</b> {1}\
  <br><b>Manual Modifier:</b> {2}\
  <br><b>Other Modifier:</b> {3}\
  <br><b>Total:</b> {4}</html>
