# Copyright (C) 2005-2026 The MegaMek Team. All Rights Reserved.
#
# This file is part of MekHQ.
#
# MekHQ is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License (GPL),
# version 3 or (at your option) any later version,
# as published by the Free Software Foundation.
#
# MekHQ is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# A copy of the GPL should have been included with this project;
# if not, see <https://www.gnu.org/licenses/>.
#
# NOTICE: The MegaMek organization is a non-profit group of volunteers
# creating free software for the BattleTech community.
#
# MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
# of The Topps Company, Inc. All Rights Reserved.
#
# Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
# InMediaRes Productions, LLC.
#
# MechWarrior Copyright Microsoft Corporation. MegaMek was created under
# Microsoft's "Game Content Usage Rules"
# <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
# affiliated with Microsoft.
lblEmployer.text=<html><nobr><b>Employer:</b></nobr></html>
lblLocation.text=<html><nobr><b>Location:</b></nobr></html>
lblType.text=<html><nobr><b>Mission Type:</b></nobr></html>
lblStartDate.text=<html><nobr><b>Start Date:</b></nobr></html>
lblEndDate.text=<html><nobr><b>End Date:</b></nobr></html>
lblPayout.text=<html><nobr><b>Monthly Payout:</b></nobr></html>
lblCommand.text=<html><nobr><b>Command Rights:</b></nobr></html>
lblBLC.text=<html><nobr><b>Battle Loss Compensation:</b></nobr></html>
lblSalvageValueMerc.text=<html><nobr><b>Total Value Salvaged (You):</b></nobr></html>
lblSalvageValueEmployer.text=<html><nobr><b>Total Value Salvaged (Ally):</b></nobr></html>
lblSalvagePct.text=<html><nobr><b>Salvage Percentage:</b></nobr></html>
lblSalvage.text=<html><nobr><b>Salvage Rights:</b></nobr></html>
exchange=Exchange
none=None
lblEnemy.text=<html><nobr><b>Enemy:</b></nobr></html>
lblAllyRating.text=<html><nobr><b>Ally Experience & Equipment:</b></nobr></html>
lblEnemyRating.text=<html><nobr><b>Enemy Experience & Equipment:</b></nobr></html>
lblMorale.text=<html><nobr><b>Enemy Morale:</b></nobr></html>
lblScore.text=<html><nobr><b>Victory Points:</b></nobr></html>
lblSupportPoints.text=<html><nobr><b>Support Points:</b></nobr></html>
lblNoEarlyEnd.text=(No Early Contract End)
lblDistance.text=<html><nobr><b>Estimated Days (Jumps) to Location:</b></nobr></html>
lblOverhead.text=<html><nobr><b>Overhead Compensation:</b></nobr></html>
lblSupport.text=<html><nobr><b>StraightSupport:</b></nobr></html>
lblSharePct.text=<html><nobr><b>Shares:</b></nobr></html>
lblCargoRequirement.text=<html><nobr><b>Convoy Cargo Size:</b></nobr></html>
txtGarrisonMoraleRouted.text=Peaceful
txtGarrisonMoraleRouted.tooltip=There is no enemy activity in the Area of Operations.
