# Copyright (C) 2026 The MegaMek Team. All Rights Reserved.
#
# This file is part of MekHQ.
#
# MekHQ is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License (GPL),
# version 3 or (at your option) any later version,
# as published by the Free Software Foundation.
#
# MekHQ is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# A copy of the GPL should have been included with this project;
# if not, see <https://www.gnu.org/licenses/>.
#
# NOTICE: The MegaMek organization is a non-profit group of volunteers
# creating free software for the BattleTech community.
#
# MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
# of The Topps Company, Inc. All Rights Reserved.
#
# Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
# InMediaRes Productions, LLC.
#
# MechWarrior Copyright Microsoft Corporation. MegaMek was created under
# Microsoft's "Game Content Usage Rules"
# <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
# affiliated with Microsoft.
# suppress inspection "UnusedProperty" for the whole file
IndependentEmployerTableValue.NOBLE.name=Noble
IndependentEmployerTableValue.NOBLE.tooltip=A landed noble or house lord hiring on their personal authority.
IndependentEmployerTableValue.PLANETARY_GOVERNMENT.name=Planetary Government
IndependentEmployerTableValue.PLANETARY_GOVERNMENT.tooltip=The ruling government of a single world, acting on its own behalf.
IndependentEmployerTableValue.MERCENARY.name=Mercenary
IndependentEmployerTableValue.MERCENARY.tooltip=Another mercenary command subcontracting the work to your unit.
IndependentEmployerTableValue.MAJOR_PERIPHERY.name=Major Periphery
IndependentEmployerTableValue.MAJOR_PERIPHERY.tooltip=A major Periphery state beyond the borders of the Inner Sphere.
IndependentEmployerTableValue.MINOR_PERIPHERY.name=Minor Periphery
IndependentEmployerTableValue.MINOR_PERIPHERY.tooltip=A minor Periphery realm or independent world on the fringe of known space.
IndependentEmployerTableValue.CORPORATION.name=Corporation
IndependentEmployerTableValue.CORPORATION.tooltip=A megacorporation or interstellar business concerns hiring private muscle.
