# Copyright (C) 2005-2026 The MegaMek Team. All Rights Reserved.
#
# This file is part of MekHQ.
#
# MekHQ is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License (GPL),
# version 3 or (at your option) any later version,
# as published by the Free Software Foundation.
#
# MekHQ is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# A copy of the GPL should have been included with this project;
# if not, see <https://www.gnu.org/licenses/>.
#
# NOTICE: The MegaMek organization is a non-profit group of volunteers
# creating free software for the BattleTech community.
#
# MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
# of The Topps Company, Inc. All Rights Reserved.
#
# Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
# InMediaRes Productions, LLC.
#
# MechWarrior Copyright Microsoft Corporation. MegaMek was created under
# Microsoft's "Game Content Usage Rules"
# <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
# affiliated with Microsoft.
# Column names
Column.PERSON.title=Person
Column.RANK.title=Rank
Column.FIRST_NAME.title=First Name
Column.LAST_NAME.title=Last Name
Column.PRE_NOMINAL.title=Pre-Nominal
Column.GIVEN_NAME.title=Given Name
Column.SURNAME.title=Surname
Column.BLOODNAME.title=Bloodname
Column.POST_NOMINAL.title=Post-Nominal
Column.CALLSIGN.title=Callsign
Column.AGE.title=Age
Column.PERSONNEL_STATUS.title=Status
Column.GENDER.title=Gender
Column.SKILL_LEVEL.title=Skill Level
Column.PERSONNEL_ROLE.title=Profession
Column.UNIT_ASSIGNMENT.title=Unit Assignment
Column.FORCE.title=Formation
Column.DEPLOYED.title=Deployed
Column.MEK.title=Mek
Column.GROUND_VEHICLE.title=Vehicle
Column.NAVAL_VEHICLE.title=Naval
Column.VTOL.title=VTOL
Column.AEROSPACE.title=Aero
Column.CONVENTIONAL_AIRCRAFT.title=Aircraft
Column.VESSEL.title=Spacecraft
Column.PROTOMEK.title=ProtoMek
Column.BATTLE_ARMOUR.title=Battle Armour
Column.AGGREGATE_COMBAT.title=Combat
Column.SMALL_ARMS.title=Infantry Gunnery
Column.ANTI_MEK.title=Anti-Mek
Column.ARTILLERY.title=Artillery
Column.NAVIGATION.title=Navigation
Column.TACTICS.title=Tactics
Column.STRATEGY.title=Strategy
Column.LEADERSHIP.title=Leadership
Column.SCOUTING.title=Scouting
Column.ASTECH.title=AsTech
Column.TECH_MEK.title=Tech/Mek
Column.TECH_AERO.title=Tech/Aero
Column.TECH_MECHANIC.title=Mechanic
Column.TECH_BA.title=Tech/BA
Column.TECH_VESSEL.title=Tech/Vessel
Column.ZERO_G.title=Zero-G Ops
Column.MEDTECH.title=MedTech
Column.MEDICAL.title=Surgery
Column.WORK_MINUTES.title=Minutes
Column.TECH_MINUTES.title=Max Minutes
Column.MEDICAL_CAPACITY.title=Max Patients
Column.APPRAISAL.title=Appraisal
Column.TRAINING.title=Training
Column.ADMINISTRATION.title=Admin
Column.NEGOTIATION.title=Negotiation
Column.INJURIES.title=Injuries
Column.KILLS.title=Kills
Column.SALARY.title=Salary
Column.XP.title=XP
Column.ORIGIN_FACTION.title=Origin Faction
Column.ORIGIN_PLANET.title=Origin Planet
Column.BIRTHDAY.title=Birthday
Column.RECRUITMENT_DATE.title=Recruitment Date
Column.LAST_RANK_CHANGE_DATE.title=Last Rank Change
Column.DUE_DATE.title=Due Date
Column.RETIREMENT_DATE.title=Retirement Date
Column.DEATH_DATE.title=Death Date
Column.COMMANDER.title=Commander
Column.FOUNDER.title=Founder
Column.CLAN_PERSONNEL.title=Clan Personnel
Column.WANTS_CHILDREN.title=Wants Children
Column.IMMORTAL.title=Excluded from Random Death
Column.HIDE_PERSONALITY.title=Hide Personality
Column.NEVER_ASSIGN_AUTO_MAINTENANCE.title=Tech Auto Assign Ignore
Column.PREFERS_MEN.title=Prefers Men
Column.PREFERS_WOMEN.title=Prefers Women
Column.QUICK_TRAIN_IGNORE.title=Quick Train Ignore
Column.SALVAGE_SUPERVISOR.title=Salvage Supervisor
Column.SECOND_IN_COMMAND.title=Second-in-Command
Column.UNDER_PROTECTION.title=Under Protection
Column.COVER_MEDICAL_EXPENSES.title=Cover Medical Expenses
Column.BLOCK_MATERNITY_LEAVE.title=Block Maternity Leave
Column.TOUGHNESS.title=Toughness
Column.CONNECTIONS.title=Connections
Column.WEALTH.title=Wealth
Column.EXTRA_INCOME.title=Extra Income
Column.REPUTATION.title=Reputation
Column.UNLUCKY.title=Unlucky
Column.BLOODMARK.title=Bloodmark
Column.FATIGUE.title=Fatigue
Column.EDGE.title=Edge
Column.SPA_COUNT.title=SPA Count
Column.IMPLANT_COUNT.title=Implant Count
Column.MODIFICATION_COUNT.title=Modification Count
Column.LOYALTY.title=Loyalty
Column.HIGHEST_EDUCATION.title=Highest Education
Column.CURRENT_EDUCATION.title=Current Education
Column.ACADEMY.title=Academy
Column.COURSE.title=Course
Column.ACADEMY_DURATION.title=Remaining
Column.AGGRESSION.title=Aggression
Column.AMBITION.title=Ambition
Column.GREED.title=Greed
Column.SOCIAL.title=Social
Column.REASONING.title=Talent
Column.STRENGTH.title=Strength
Column.BODY.title=Body
Column.REFLEXES.title=Reflexes
Column.DEXTERITY.title=Dexterity
Column.INTELLIGENCE.title=Intelligence
Column.WILLPOWER.title=Willpower
Column.CHARISMA.title=Charisma
Column.SHIP_TRANSPORT.title=Transport Ship
Column.TACTICAL_TRANSPORT.title=Tactical Transport
Column.LOCATION_SYSTEM.title=System
Column.LOCATION_PLANET.title=Planet
Column.LOCATION_NAME.title=Location Name
Column.DESTINATION_SYSTEM.title=Dest. System
Column.DESTINATION_PLANET.title=Dest. Planet
Column.DESTINATION_NAME.title=Dest. Name
Column.IS_MARRIED.title=Married?
Column.FORMER_SPOUSES.title=Ex-Spouses
Column.IMMEDIATE_FAMILY.title=Immediate Family
Column.EXTENDED_FAMILY.title=Extended Family
Column.TOTAL_RELATIVES.title=Total Relatives
# Cell text
Cell.SURNAME.Soldiers.suffix=(+{0} soldiers)
Cell.SURNAME.Crew.suffix=(+{0} crew)
Cell.WANTS_CHILDREN.dueText=Due: {0}
