# Copyright (C) 2025-2026 The MegaMek Team. All Rights Reserved.
#
# This file is part of MekHQ.
#
# MekHQ is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License (GPL),
# version 3 or (at your option) any later version,
# as published by the Free Software Foundation.
#
# MekHQ is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# A copy of the GPL should have been included with this project;
# if not, see <https://www.gnu.org/licenses/>.
#
# NOTICE: The MegaMek organization is a non-profit group of volunteers
# creating free software for the BattleTech community.
#
# MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
# of The Topps Company, Inc. All Rights Reserved.
#
# Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
# InMediaRes Productions, LLC.
#
# MechWarrior Copyright Microsoft Corporation. MegaMek was created under
# Microsoft's "Game Content Usage Rules"
# <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
# affiliated with Microsoft.
# suppress inspection "UnusedMessageFormatParameter" for whole file
# suppress inspection "UnusedProperty" for whole file
NONE.label=None
ADJUSTS_CLOTHES.label=Constantly Adjusting Clothes
AFFECTIONATE.label=Overly Affectionate
APOLOGETIC.label=Overly Apologetic
BOOKWORM.label=Always Reading
CALENDAR.label=Keeps a Personal Calendar
CANDLES.label=Fond of Scented Candles
CHEWING_GUM.label=Always Chewing Gum
CHRONIC_LATENESS.label=Chronically Late
CLEANER.label=Compulsive Cleaner
COLLECTOR.label=Collects Odd Items
COMPETITIVE_NATURE.label=Competitive Nature
COMPLIMENTS.label=Excessive Complimenter
DAYDREAMER.label=Prone to Daydreaming
DOODLER.label=Compulsive Doodler
DOOLITTLE.label=Talks to Animals
DRAMATIC.label=Overly Dramatic
EATING_HABITS.label=Unpredictable Eating Habits
ENVIRONMENTAL_SENSITIVITY.label=Extreme Environmental Sensitivity
EXCESSIVE_CAUTION.label=Excessively Cautious
EXCESSIVE_GREETING.label=Over-the-Top Greetings
EYE_CONTACT.label=Maintains Intense Eye Contact
FASHION_CHOICES.label=Eccentric Fashion Choices
FIDGETS.label=Constantly Fidgeting
FITNESS.label=Extreme Personal Fitness Routine
FIXATES.label=Fixates on One Topic
FLASK.label=Carries a Flask
FOOT_TAPPER.label=Always Tapping Foot
FORGETFUL.label=Chronically Forgetful
FORMAL_SPEECH.label=Overly Formal Speech Pattern
FURNITURE.label=Constantly Rearranges Furniture
GLASSES.label=Constantly Adjusts Glasses
GLOVES.label=Always Wearing Gloves
HAND_GESTURES.label=Excessive Hand Gestures
HAND_WRINGER.label=Compulsive Hand-Wringer
HANDSHAKE.label=Overly Enthusiastic Handshake
HEADPHONES.label=Always Wearing Headphones
HEALTHY_SNACKS.label=Frequently Snacking on Healthy Foods
HISTORIAN.label=Passionate about History
HUMMER.label=Habitual Hummer
HYGIENIC.label=Obsessed with Hygiene
IRREGULAR_SLEEPER.label=Unusual Sleep Patterns
JOKER.label=Fond of Puns
LISTS.label=Compulsive List Maker
LITERAL.label=Overly Literal
LOCKS.label=Checks Locks Repeatedly
MEASURED_TALKER.label=Tends to Speak in a Measured Pace
MINIMALIST.label=Extreme Minimalist
MUG.label=Prefers Using a Specific Mug
NAIL_BITER.label=Constant Nail Biter
NICKNAMING.label=Frequent Nicknaming
NIGHT_OWL.label=Night Owl
NOTE_TAKER.label=Compulsive Note-Taking
NOTEBOOK.label=Always Carrying a Notebook
OBJECT.label=Carries a Personal Object
ORGANIZATIONAL_TENDENCIES.label=Obsessive Tendencies
ORGANIZER.label=Always Organizing
ORIGAMI.label=Fond of Origami
OVER_PLANNER.label=Obsessive Over-Planner
OVEREXPLAINER.label=Chronic Overexplainer
PEN_CLICKER.label=Habitual Pen Clicker
PEN_TWIRLER.label=Habitual Pen Twirler
PERSONIFICATION.label=Overly Friendly with Equipment
PESSIMIST.label=Habitual Pessimist
PHRASES.label=Tends to Use Specific Phrases
PLANTS.label=Loves Plants
POLITE.label=Excessive Politeness
PRACTICAL_JOKER.label=Loves Practical Jokes
PREPARED.label=Always Prepared
PUNCTUAL.label=Overly Punctual
PUZZLES.label=Obsessed with Puzzles
QUOTES.label=Collects Quotes
RARELY_SLEEPS.label=Rarely Sleeps
ROUTINE.label=Has a Routine for Small Tasks
SEEKS_APPROVAL.label=Constantly Seeking Approval
SENTIMENTAL.label=Overly Sentimental
SHARPENING.label=Compulsive Sharpening
SINGS.label=Sings to Themselves
SKEPTICAL.label=Chronically Skeptical
SLEEP_TALKER.label=Talks in Sleep
SMILER.label=Compulsive Smiler
SNACKS.label=Always Has a Snack
STORYTELLING.label=Compulsive Storytelling
STRETCHING.label=Constantly Stretching
SUPERSTITIOUS_RITUALS.label=Suspicious Rituals
SUPERVISED_HABITS.label=Highly Supervised Habits
TECH_TALK.label=Incessant Tech Talk
TECHNOPHOBIA.label=Phobia of Technology
THESAURUS.label=Uses Obscure Words
THIRD_PERSON.label=Speaks in Third Person
TIME_MANAGEMENT.label=Obsessed with Time Management
TINKERER.label=Compulsive Tinkerer
TRUTH_TELLER.label=Habitual Truth-Teller
UNNECESSARY_CAUTION.label=Unnecessarily Cautious
UNPREDICTABLE_SPEECH.label=Speaks Unpredictably
UNUSUAL_HOBBIES.label=Unusual Hobbies
WATCH.label=Constantly Checking the Time
WEATHERMAN.label=Obsessed with Weather
WHISTLER.label=Frequent Whistler
WORRIER.label=Persistent Worrier
WRITER.label=Aspiring Writer
BATTLEFIELD_NOSTALGIA.label=Constantly Reminiscing
HEAVY_HANDED.label=Heavy-Handed With Equipment
RATION_HOARDER.label=Hoards Rations
EMERGENCY_MANUAL_READER.label=Obsessive Manual Reader
QUICK_TO_QUIP.label=Quick to Make Jokes
TECH_SKEPTIC.label=Distrusts New Technology
POST_BATTLE_RITUALS.label=Performs Post-Battle Rituals
OVER_COMMUNICATOR.label=Over-Explains
FIELD_MEDIC.label=Tends to Perform Medical Aid
SYSTEM_CALIBRATOR.label=Constantly Calibrates Systems
AMMO_COUNTER.label=Obsessive Counter
BRAVADO.label=Excessive Bravado
COMBAT_SONG.label=Sings During Engagements
COMMS_TOGGLE.label=Constantly Toggles Comms Channels
EJECTION_READY.label=Paranoid About Emergency Systems
HAND_SIGNS.label=Uses Elaborate Hand Signals
HATE_FOR_MEKS.label=Harbors a Deep Hatred for 'Meks
IMPROVISED_WEAPONRY.label=Uses Improvised Weaponry
PRE_BATTLE_SUPERSTITIONS.label=Believes in Omens
SILENT_LEADER.label=Silent Leader
BATTLE_CRITIC.label=Constant Critic
CHECKS_WEAPON_SAFETY.label=Constantly Performs Safety Checks
CLOSE_COMBAT_PREF.label=Prefers Things Up Close
COMBAT_POET.label=Recites Poetry
CUSTOM_DECALS.label=Obsessed with Custom Decals
DISPLAYS_TROPHIES.label=Displays Trophies from Past Accomplishments
DO_IT_YOURSELF.label=Obsessive Do-It-Yourselfer
FIELD_IMPROVISER.label=Improvises with Field Supplies
LOUD_COMMS.label=Uses Loud Comms
WAR_STORIES.label=Overly Fond of War Stories
ALL_OR_NOTHING.label=All or Nothing Personality
BOOTS_ON_THE_GROUND.label=Prefers Ground Combat
BRAVERY_BOASTER.label=Boasts About Bravery
COCKPIT_DRIFTER.label=Daydreams
CONSPIRACY_THEORIST.label=Believes in Conspiracy Theories
DEVOUT_WARRIOR.label=Code of Honor
DUAL_WIELDING.label=Obsessed with Multitasking
EMBLEM_LOVER.label=Attached to a Personal Emblem
EXCESSIVE_DEBRIEFING.label=Obsessive Debriefer
EYE_FOR_ART.label=Appreciates Battlefield Scenery
FAST_TALKER.label=Talks Very Fast
FINGER_GUNS.label=Uses Finger Guns
FLARE_DEPLOYER.label=Excessive NavPoint Use
FRIENDLY_INTERROGATOR.label=Likes to "Interrogate" Teammates
GUN_NUT.label=Fascinated by Ancient Firearms
LAST_MAN_STANDING.label=Survivor Mentality
LEGENDARY_MEK.label=Believes in the Black Marauder
PASSIVE_LEADER.label=Leads Through Passivity
REBEL_WITHOUT_CAUSE.label=Rebellious Without Cause
SIMPLE_LIFE.label=Prefers Simple Solutions
ANTI_AUTHORITY.label=Distrusts Authority
BLOODLUST.label=Thrives in Chaos
BRAVERY_IN_DOUBT.label=Acts Bravely When Doubted
CLOSE_QUARTERS_ONLY.label=Obsesses over Duels
COOL_UNDER_FIRE.label=Remains Calm Under Fire
CRASH_TEST.label=Purposely Tests Equipment Durability
DEAD_PAN_HUMOR.label=Uses Deadpan Humor
DRILLS.label=Obsessed with Drills and Simulations
ENEMY_RESPECT.label=Respects Worthy Enemies
EXTREME_MORNING_PERSON.label=Extremely Morning-Oriented
GALLANT.label=Gallant in Battle
IRON_STOMACH.label=Can Eat Anything
MISSION_CRITIC.label=Hyper-Critical of Mission Plans
NO_PAIN_NO_GAIN.label=Believes in "No Pain, No Gain"
PERSONAL_ARMORY.label=Keeps a Personal Armory
QUICK_ADAPTER.label=Adapts Quickly to New Situations
RETALIATOR.label=Seeks Revenge for Any Slight
RUSH_HOUR.label=Enjoys the Rush of a Crisis
SILENT_PROTECTOR.label=Protects Allies Silently
ALWAYS_TACTICAL.label=Always Thinking Tactically
BATTLE_SCREAM.label=Uses a Battle Scream
BRIEF_AND_TO_THE_POINT.label=Brief and To the Point
CALLSIGN_COLLECTOR.label=Collects Callsigns
CHATTERBOX.label=Constant Chatterbox
COMBAT_ARTIST.label=Sees Combat as Art Form
DARING_ESCAPE.label=Specializes in Daring Escapes
DOOMSDAY_PREPPER.label=Doomsday Prepper
EQUIPMENT_SCAVENGER.label=Scavenges for Gear
FRIEND_TO_FOES.label=Sympathetic to Enemies
GUNG_HO.label=Gung-Ho Attitude
INSPIRATIONAL_POET.label=Gives Inspirational Speeches
MEK_MATCHMAKER.label=Believes in 'Mek Compatibility
MISSILE_JUNKIE.label=Overkill Enthusiast
NEVER_RETREAT.label=Hates to Give Up
OPTIMISTIC_TO_A_FAULT.label=Optimistic to a Fault
REACTIVE.label=Highly Strung
RISK_TAKER.label=Extreme Risk Taker
SIGNATURE_MOVE.label=Has a Signature Move
TACTICAL_WITHDRAWAL.label=Withdraws from Conflict
ACCENT_SWITCHER.label=Switches Accents Randomly
AMBUSH_LOVER.label=Walks Softly
BATTLE_HARDENED.label=Battle-Hardened Stoic
BREAKS_RADIO_SILENCE.label=Breaks Radio Silence
CONVOY_LOVER.label=Prefers Convoy Missions
CAMOUFLAGE.label=Likes to Blend In
DISTANT_LEADER.label=Leads from a Distance
DRAMATIC_FINISH.label=Prefers Dramatic Finishes
ENGINE_REVERER.label=Emphatic with Technology
FLIRTY_COMMS.label=Flirts Over Comms
FOCUS_FREAK.label=Hyper-Focused Under Pressure
FOUL_MOUTHED.label=Foul-Mouthed
FREESTYLE_COMBAT.label=Has a Freestyle Approach
GEOMETRY_GURU.label=Geometry Guru
ICE_COLD.label=Emotionless in Crisis
PICKY_ABOUT_GEAR.label=Extremely Picky
RECORD_KEEPER.label=Statistics Nerd
RESOURCE_SCROUNGER.label=Resourceful
TRASH_TALKER.label=Relentless Trash Talker
CORRECTS_PRONOUNS.label=Quick to Correct Pronouns
BODY_DISCOMFORT.label=Uncomfortable in Their Own Body
MEK_COMFORT.label=Uncomfortable Off-Duty
FEAR_OF_FIRE.label=Fear of Fire
TOUCH_SENSITIVE.label=Touch Sensitive
HOLOVID_FANATIC.label=Holovid Fanatic
INVINCIBLE.label=Convinced They're Invincible
STUTTERS.label=Stutters
ACROPHOBIA.label=Afraid of Heights
CLAUSTROPHOBIA.label=Fear of Enclosed Spaces
AGORAPHOBIA.label=Fear of Open Spaces
NYCTOPHOBIA.label=Fear of the Dark
MONOPHOBIA.label=Fear of Being Alone
HEMOPHOBIA.label=Fear of Blood
ZERO_G_PARALYSIS.label=Fear of Zero-G
HEDONIST.label=Hedonist
BROADCASTS_MUSIC.label=Broadcasts Music
NEMESIS.label=Has a Nemesis
FEAR_MEKS.label=Fear of Mek
LOCAL_CONNECTOR.label=Local Connector
HATRED.label=Hates the Enemy
PANTSLESS.label=Refuses to Wear Pants
MAKES_CLOTHES.label=Makes Clothes for Others
ACTS_SUSPICIOUSLY.label=Acts Suspiciously
NIGHTMARES.label=Suffers from Nightmares
FREEZES.label=Freezes Up
TRAUMATIZED.label=Traumatized By The Past
HAUNTED.label=Has Haunted Dreams
BROKEN.label=Broken by the Past
REGRETS.label=Regrets a Terrible Crime
DARK_SECRET.label=Has a Dark Secret
ANTHROPOMORPHIC.label=Likes Anthropomorphic Animals
CLUMSY.label=Overwhelming Clumsy
JUSTIFIES.label=Believes the End Justifies the Means
ENJOYS_DRAMA.label=Enjoys Causing Interpersonal Drama
