# Copyright (C) 2026 The MegaMek Team. All Rights Reserved.
#
# This file is part of MekHQ.
#
# MekHQ is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License (GPL),
# version 3 or (at your option) any later version,
# as published by the Free Software Foundation.
#
# MekHQ is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# A copy of the GPL should have been included with this project;
# if not, see <https://www.gnu.org/licenses/>.
#
# NOTICE: The MegaMek organization is a non-profit group of volunteers
# creating free software for the BattleTech community.
#
# MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
# of The Topps Company, Inc. All Rights Reserved.
#
# Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
# InMediaRes Productions, LLC.
#
# MechWarrior Copyright Microsoft Corporation. MegaMek was created under
# Microsoft's "Game Content Usage Rules"
# <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
# affiliated with Microsoft.
# suppress inspection "UnusedProperty" for the whole file
RandomDeathAnnouncement.response=Unfortunate
RandomDeathAnnouncement.inCharacter.unemployed=<h2 style="text-align:center;">AUTOMATED MEDICAL ALERT</h2>\
  <b>Patient:</b> {0}<br>\
  <b>Cause of Death:</b> {1}<br>\
  <b>Profession/s:</b> {2}<br>\
  <b>Age at Death:</b> {3}<br>\
  <b>Years in Campaign:</b> {4}<br>
RandomDeathAnnouncement.inCharacter.employed=<h2 style="text-align:center;">AUTOMATED MEDICAL ALERT</h2>\
  <b>Patient:</b> {0}<br>\
  <b>Cause of Death:</b> {1}<br>\
  <b>Profession/s:</b> {2}<br>\
  <b>Age at Death:</b> {3}<br>\
  <b>Years in Campaign:</b> {4}<br>\
  <b>Years in Service:</b> {5}<br>\
  <b>Total XP Earnings:</b> {6}<br>\
  <b>Total Financial Earnings:</b> {7} C-Bills
RandomDeathAnnouncement.outOfCharacter=Cause of death is for roleplay purposes only.\
  <p>There are multiple triggers for this nag, one for combat personnel, techs, non-tech support, civilians, camp \
  followers, and retirees. All must be disabled in MekHQ Client Options before these nags will stop appearing. This \
  nag was triggered as the character is classified as {0}.\</p>\
  <p>If you accidentally suppress this warning, you can re-enable it in MekHQ Client Options.</p>
RandomDeathAnnouncement.outOfCharacter.NAG_SOMEONE_RANDOMLY_DIED_CAMP_FOLLOWER=a <b>Camp Follower</b>
RandomDeathAnnouncement.outOfCharacter.NAG_SOMEONE_RANDOMLY_DIED_RETIREE=a <b>Retiree</b>
RandomDeathAnnouncement.outOfCharacter.NAG_SOMEONE_RANDOMLY_DIED_COMBAT=<b>Combat Personnel</b>
RandomDeathAnnouncement.outOfCharacter.NAG_SOMEONE_RANDOMLY_DIED_TECH=<b>Tech Personnel</b>
RandomDeathAnnouncement.outOfCharacter.NAG_SOMEONE_RANDOMLY_DIED_OTHER_SUPPORT=<b>Non-Tech Support Personnel</b>
RandomDeathAnnouncement.outOfCharacter.NAG_SOMEONE_RANDOMLY_DIED_CIVILIAN=a <b>Civilian</b>
