# FateChartOdds
FateChartOdds.IMPOSSIBLE.label=Impossible
FateChartOdds.NEARLY_IMPOSSIBLE.label=Nearly Impossible
FateChartOdds.VERY_UNLIKELY.label=Very Unlikely
FateChartOdds.UNLIKELY.label=Unlikely
FateChartOdds.FIFTY_FIFTY.label=50/50
FateChartOdds.LIKELY.label=Likely
FateChartOdds.VERY_LIKELY.label=Very Likely
FateChartOdds.NEARLY_CERTAIN.label=Nearly Certain
FateChartOdds.CERTAIN.label=Certain
# FateChartAnswer
FateChartAnswer.EXCEPTIONAL_YES.label=Exceptional Yes
FateChartAnswer.NORMAL_YES.label=Yes
FateChartAnswer.NORMAL_NO.label=No
FateChartAnswer.EXCEPTIONAL_NO.label=Exceptional No
# RandomEventFocus
RandomEventFocus.REMOTE_EVENT.label=Remote Event
RandomEventFocus.AMBIGUOUS_EVENT.label=Ambiguous Event
RandomEventFocus.NEW_NPC.label=New NPC
RandomEventFocus.NPC_ACTION.label=NPC Action
RandomEventFocus.NPC_NEGATIVE.label=NPC Negative
RandomEventFocus.NPC_POSITIVE.label=NPC Positive
RandomEventFocus.MOVE_TOWARD_A_THREAD.label=Move Toward A Thread
RandomEventFocus.MOVE_AWAY_FROM_A_THREAD.label=Move Away From A Thread
RandomEventFocus.CLOSE_A_THREAD.label=Close A Thread
RandomEventFocus.PC_NEGATIVE.label=PC Negative
RandomEventFocus.PC_POSITIVE.label=PC Positive
RandomEventFocus.CURRENT_CONTEXT.label=Current Context
