# FateChartOdds
FateChartOdds.IMPOSSIBLE.label=Impossible
FateChartOdds.NEARLY_IMPOSSIBLE.label=Nearly Impossible
FateChartOdds.VERY_UNLIKELY.label=Very Unlikely
FateChartOdds.UNLIKELY.label=Unlikely
FateChartOdds.FIFTY_FIFTY.label=50/50
FateChartOdds.LIKELY.label=Likely
FateChartOdds.VERY_LIKELY.label=Very Likely
FateChartOdds.NEARLY_CERTAIN.label=Nearly Certain
FateChartOdds.CERTAIN.label=Certain
# FateChartAnswer
FateChartAnswer.EXCEPTIONAL_YES.label=Exceptional Yes
FateChartAnswer.NORMAL_YES.label=Yes
FateChartAnswer.NORMAL_NO.label=No
FateChartAnswer.EXCEPTIONAL_NO.label=Exceptional No
