# Copyright (C) 2026 The MegaMek Team. All Rights Reserved.
#
# This file is part of MekHQ.
#
# MekHQ is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License (GPL),
# version 3 or (at your option) any later version,
# as published by the Free Software Foundation.
#
# MekHQ is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# A copy of the GPL should have been included with this project;
# if not, see <https://www.gnu.org/licenses/>.
#
# NOTICE: The MegaMek organization is a non-profit group of volunteers
# creating free software for the BattleTech community.
# Template properties panel
TemplatePropertiesPanel.scenarioName.label=Scenario Name:
TemplatePropertiesPanel.shortBriefing.label=Short Briefing:
TemplatePropertiesPanel.detailedBriefing.label=Detailed Briefing:
TemplatePropertiesPanel.scenarioType.label=Scenario Type:
TemplatePropertiesPanel.battlefieldControl.label=Battlefield Control:
TemplatePropertiesPanel.hostileFacility.label=Hostile Facility
TemplatePropertiesPanel.alliedFacility.label=Allied Facility
TemplatePropertiesPanel.suitedForAmbushes.label=Suited for Ambushes
TemplatePropertiesPanel.suitedForBungledPatrols.label=Suited for Bungled Patrols
# Map parameters panel
MapParametersPanel.title=Scenario Map Parameters:
MapParametersPanel.baseWidth.label=Base Width:
MapParametersPanel.baseHeight.label=Base Height:
MapParametersPanel.widthIncrement.label=Scaled Width Increment:
MapParametersPanel.heightIncrement.label=Scaled Height Increment:
MapParametersPanel.additionalMapSheetWide.label=Additional Map Sheets Wide:
MapParametersPanel.additionalMapSheetWide.tooltip=Extra map sheets added to the map's width beyond the base/scaled size.
MapParametersPanel.additionalMapSheetTall.label=Additional Map Sheets Tall:
MapParametersPanel.additionalMapSheetTall.tooltip=Extra map sheets added to the map's height beyond the base/scaled size.
MapParametersPanel.allowRotation.label=Allow 90 Degree Rotation:
MapParametersPanel.useAtBSizing.label=Use AtB Base Dimensions:
MapParametersPanel.useAtBSizing.tooltip=Use the AtB Map Sizes table to determine the base width and height of the map.
MapParametersPanel.allowedMapTypes.label=Allowed Map Types:
MapParametersPanel.anyGroundMap.label=Any Ground Map
MapParametersPanel.useSpaceMap.label=Use Space Map
MapParametersPanel.useLowAtmoMap.label=Use Low Atmo Map
MapParametersPanel.specificMapTypes.label=Specific Map Types
# Modifiers panel
ModifiersPanel.title=Fixed Modifiers
ModifiersPanel.add=Add
ModifiersPanel.remove=Remove
