# Copyright (C) 2026 The MegaMek Team. All Rights Reserved.
#
# This file is part of MekHQ.
#
# MekHQ is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License (GPL),
# version 3 or (at your option) any later version,
# as published by the Free Software Foundation.
#
# MekHQ is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# A copy of the GPL should have been included with this project;
# if not, see <https://www.gnu.org/licenses/>.
#
# NOTICE: The MegaMek organization is a non-profit group of volunteers
# creating free software for the BattleTech community.
#
# MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
# of The Topps Company, Inc. All Rights Reserved.
#
# Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
# InMediaRes Productions, LLC.
#
# MechWarrior Copyright Microsoft Corporation. MegaMek was created under
# Microsoft's "Game Content Usage Rules"
# <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
# affiliated with Microsoft.
# suppress inspection "UnusedProperty" for the whole file
StartingSystemConfirmationDialog.text=Would you like to start your campaign in a semi-randomized location?\
  <p>If you decline, you will start in your current faction's system. Otherwise, a random Inner Sphere faction will \
  be chosen, and you will start on their capital, instead.</p>\
  <p>Random starts can be a fantastic way to help made each campaign feel distinct.</p>
StartingSystemConfirmationDialog.button.confirm=Use a Random Starting System
StartingSystemConfirmationDialog.button.decline=Start in {0}
StartingSystemConfirmationDialog.button.decline.unknown=ERROR: Unknown starting system
