# Copyright (C) 2025-2026 The MegaMek Team. All Rights Reserved.
#
# This file is part of MekHQ.
#
# MekHQ is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License (GPL),
# version 3 or (at your option) any later version,
# as published by the Free Software Foundation.
#
# MekHQ is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# A copy of the GPL should have been included with this project;
# if not, see <https://www.gnu.org/licenses/>.
#
# NOTICE: The MegaMek organization is a non-profit group of volunteers
# creating free software for the BattleTech community.
#
# MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
# of The Topps Company, Inc. All Rights Reserved.
#
# Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
# InMediaRes Productions, LLC.
#
# MechWarrior Copyright Microsoft Corporation. MegaMek was created under
# Microsoft's "Game Content Usage Rules"
# <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
# affiliated with Microsoft.
StratConRulesManager.scoutingSkillCheck=Advanced Scouting
StratConRulesManager.tacticsSkillCheck=Reinforcement Check
StratConRulesManager.combatBonus.reason=Combat bonus: {0}
StratConRulesManager.combatBonus.report=Earned a combat bonus of {0} for securing an essential objective.
StratConPointOfInterestRules.expired.report=The point of interest {0} in {1} is no longer available.
StratConDataCacheBehavior.objective=Retrieve the data cache
StratConDataCacheBehavior.secured.report=Our forces have secured the {0} in {1}.
StratConDataCacheBehavior.contested.report=Enemy forces are contesting the {0} in {1}. Win the battle to secure it.
StratConDataCacheBehavior.lost.report=The {0} in {1} has been lost.
StratConLookoutPointBehavior.objective=Observe enemy movements from the lookout point
StratConLookoutPointBehavior.secured.report=Our forces have observed enemy movements from the {0} in {1}.
StratConLookoutPointBehavior.ambush.report=The {0} in {1} was being watched! Enemy forces have ambushed our \
  observers.
StratConLookoutPointBehavior.ambushSpent.report=The {0} in {1} has been compromised and can no longer be used.
StratConPotentialLeadBehavior.objective=Follow up the potential lead
StratConPotentialLeadBehavior.dud.report=The {0} in {1} was a dud. There is no mole to be found there.
StratConPotentialLeadBehavior.contested.report=The {0} in {1} has panned out! The mole has been found, and is not \
  going quietly.
StratConPotentialLeadBehavior.secured.report=Our forces have run down the mole behind the {0} in {1}.
StratConPotentialLeadBehavior.lost.report=The mole behind the {0} in {1} has escaped.
StratConVulnerableInfrastructureBehavior.objective=Destroy the vulnerable infrastructure
StratConVulnerableInfrastructureBehavior.secured.report=Our forces have destroyed the {0} in {1}.
StratConVulnerableInfrastructureBehavior.ambush.report=The {0} in {1} was a trap! Enemy forces were lying in wait.
StratConVulnerableInfrastructureBehavior.ambushSpent.report=The trap at the {0} in {1} has been sprung. It was a decoy, \
  and there is nothing left there worth destroying.
