WarriorsAlmanacDialog.title=<h1 style="text-align:center;">Warrior's Almanac {0}</h1>
WarriorsAlmanacDialog.blurb=Welcome to the Warrior's Almanac. A trusted and impartial source for information on \
  technologies, their rise and fall.
WarriorsAlmanacDialog.parts=<h2 style="text-align:center;">Parts</h2>
WarriorsAlmanacDialog.units=<h2 style="text-align:center;">Units</h2>
WarriorsAlmanacDialog.prototype=<h2 style="text-align:center;">Prototype</h2>
WarriorsAlmanacDialog.production=<h2 style="text-align:center;">Production</h2>
WarriorsAlmanacDialog.common=<h2 style="text-align:center;">Common</h2>
WarriorsAlmanacDialog.extinct=<h2 style="text-align:center;">Extinct</h2>
WarriorsAlmanacDialog.techBase.innerSphere=<h3>Inner Sphere</h3>
WarriorsAlmanacDialog.techBase.clan=<h3>Clan</h3>
WarriorsAlmanacDialog.techBase.mixed=<h3>Mixed</h3>
WarriorsAlmanacDialog.techBase.unknown=<h3>Unknown</h3>
