/*
 * Copyright (C) 2025 The MegaMek Team. All Rights Reserved.
 *
 * This file is part of MekHQ.
 *
 * MekHQ is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License (GPL),
 * version 3 or (at your option) any later version,
 * as published by the Free Software Foundation.
 *
 * MekHQ is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * A copy of the GPL should have been included with this project;
 * if not, see <https://www.gnu.org/licenses/>.
 *
 * NOTICE: The MegaMek organization is a non-profit group of volunteers
 * creating free software for the BattleTech community.
 *
 * MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
 * of The Topps Company, Inc. All Rights Reserved.
 *
 * Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
 * InMediaRes Productions, LLC.
 *
 * MechWarrior Copyright Microsoft Corporation. MekHQ was created under
 * Microsoft's "Game Content Usage Rules"
 * <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
 * affiliated with Microsoft.
 */
package mekhq.campaign.personnel.medical.advancedMedicalAlternate;

import static mekhq.utilities.MHQInternationalization.getFormattedTextAt;
import static mekhq.utilities.MHQInternationalization.getTextAt;
import static mekhq.utilities.ReportingUtilities.CLOSING_SPAN_TAG;
import static mekhq.utilities.ReportingUtilities.getNegativeColor;
import static mekhq.utilities.ReportingUtilities.getWarningColor;
import static mekhq.utilities.ReportingUtilities.spanOpeningWithCustomColor;

import java.util.ArrayList;
import java.util.EnumMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

import mekhq.campaign.personnel.skills.enums.SkillAttribute;
import mekhq.campaign.universe.Faction;

public enum InjuryEffect {
    NONE("NONE"),
    BLINDED("BLINDED",
          getWarningColor(),
          -3,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    COMPOUND_FRACTURE("COMPOUND_FRACTURE",
          getNegativeColor(),
          0,
          0,
          0,
          -3,
          -3,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DEAFENED("DEAFENED",
          getWarningColor(),
          -3,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    FRACTURE_JAW("FRACTURE_JAW",
          getWarningColor(),
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          -3,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    FRACTURE_LIMB("FRACTURE_LIMB",
          getWarningColor(),
          0,
          0,
          0,
          -2,
          -2,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    FRACTURE_RIB("FRACTURE_RIB",
          getWarningColor(),
          0,
          -1,
          -1,
          -1,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    FRACTURE_SKULL("FRACTURE_SKULL",
          getWarningColor(),
          0,
          0,
          0,
          0,
          0,
          -2,
          -2,
          -2,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    BRAIN_TRAUMA("BRAIN_TRAUMA",
          getNegativeColor(),
          0,
          0,
          0,
          0,
          0,
          -2,
          -2,
          -2,
          true,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    INTERNAL_BLEEDING("INTERNAL_BLEEDING",
          getNegativeColor(),
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          true,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    PUNCTURED("PUNCTURED",
          getNegativeColor(),
          0,
          -2,
          -2,
          -2,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    SEVERED("SEVERED",
          getNegativeColor(),
          0,
          0,
          0,
          -5,
          -5,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    BLOOD_LOSS("BLOOD_LOSS",
          getNegativeColor(),
          0,
          -1,
          -1,
          -1,
          -1,
          -1,
          -1,
          -1,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_DEADLY("DISEASE_DEADLY",
          getNegativeColor(),
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_GROWTHS_SLIGHT("DISEASE_GROWTHS_SLIGHT",
          getWarningColor(),
          0,
          0,
          -1,
          0,
          -1,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_GROWTHS_MODERATE("DISEASE_GROWTHS_MODERATE",
          getWarningColor(),
          0,
          0,
          -2,
          0,
          -2,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_GROWTHS_SEVERE("DISEASE_GROWTHS_SEVERE",
          getNegativeColor(),
          0,
          0,
          -3,
          0,
          -3,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_INFECTION_SLIGHT("DISEASE_INFECTION_SLIGHT",
          getWarningColor(),
          0,
          0,
          -1,
          0,
          0,
          0,
          0,
          -1,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_INFECTION_MODERATE("DISEASE_INFECTION_MODERATE",
          getWarningColor(),
          0,
          0,
          -2,
          0,
          0,
          0,
          0,
          -2,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_INFECTION_SEVERE("DISEASE_INFECTION_SEVERE",
          getNegativeColor(),
          0,
          0,
          -3,
          0,
          0,
          0,
          0,
          -3,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_HEARING_SLIGHT("DISEASE_HEARING_SLIGHT",
          getWarningColor(),
          -1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_HEARING_MODERATE("DISEASE_HEARING_MODERATE",
          getWarningColor(),
          -2,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_HEARING_SEVERE("DISEASE_HEARING_SEVERE",
          getNegativeColor(),
          -3,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_WEAKNESS_SLIGHT("DISEASE_WEAKNESS_SLIGHT",
          getWarningColor(),
          0,
          -1,
          -1,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_WEAKNESS_MODERATE("DISEASE_WEAKNESS_MODERATE",
          getWarningColor(),
          0,
          -2,
          -2,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_WEAKNESS_SEVERE("DISEASE_WEAKNESS_SEVERE",
          getNegativeColor(),
          0,
          -3,
          -3,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_SORES_SLIGHT("DISEASE_SORES_SLIGHT",
          getWarningColor(),
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          -1,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_SORES_MODERATE("DISEASE_SORES_MODERATE",
          getWarningColor(),
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          -2,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_SORES_SEVERE("DISEASE_SORES_SEVERE",
          getNegativeColor(),
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          -3,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_FLU_SLIGHT("DISEASE_FLU_SLIGHT",
          getWarningColor(),
          0,
          -1,
          -1,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_FLU_MODERATE("DISEASE_FLU_MODERATE",
          getWarningColor(),
          0,
          -2,
          -2,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_FLU_SEVERE("DISEASE_FLU_SEVERE",
          getNegativeColor(),
          0,
          -3,
          -3,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_SIGHT_SLIGHT("DISEASE_SIGHT_SLIGHT",
          getWarningColor(),
          -1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_SIGHT_MODERATE("DISEASE_SIGHT_MODERATE",
          getWarningColor(),
          -2,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_SIGHT_SEVERE("DISEASE_SIGHT_SEVERE",
          getNegativeColor(),
          -3,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_TREMORS_SLIGHT("DISEASE_TREMORS_SLIGHT",
          getWarningColor(),
          0,
          0,
          -1,
          -1,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_TREMORS_MODERATE("DISEASE_TREMORS_MODERATE",
          getWarningColor(),
          0,
          0,
          -2,
          -2,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_TREMORS_SEVERE("DISEASE_TREMORS_SEVERE",
          getNegativeColor(),
          0,
          0,
          -3,
          -3,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_BREATHING_SLIGHT("DISEASE_BREATHING_SLIGHT",
          getWarningColor(),
          0,
          -1,
          -1,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_BREATHING_MODERATE("DISEASE_BREATHING_MODERATE",
          getWarningColor(),
          0,
          -2,
          -2,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_BREATHING_SEVERE("DISEASE_BREATHING_SEVERE",
          getNegativeColor(),
          0,
          -3,
          -3,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_HEMOPHILIA_SLIGHT("DISEASE_HEMOPHILIA_SLIGHT",
          getWarningColor(),
          0,
          0,
          -1,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_HEMOPHILIA_MODERATE("DISEASE_HEMOPHILIA_MODERATE",
          getWarningColor(),
          0,
          0,
          -2,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_HEMOPHILIA_SEVERE("DISEASE_HEMOPHILIA_SEVERE",
          getNegativeColor(),
          0,
          0,
          -3,
          0,
          0,
          0,
          0,
          0,
          true,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_VENEREAL_SLIGHT("DISEASE_VENEREAL_SLIGHT",
          getWarningColor(),
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          -1,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_VENEREAL_MODERATE("DISEASE_VENEREAL_MODERATE",
          getWarningColor(),
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          -2,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    DISEASE_VENEREAL_SEVERE("DISEASE_VENEREAL_SEVERE",
          getNegativeColor(),
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          -3,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    TYPE_1_LIMB_REPLACEMENT("TYPE_1_LIMB_REPLACEMENT",
          "",
          0,
          -2,
          0,
          -4,
          -4,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    TYPE_2_LIMB_REPLACEMENT("TYPE_2_LIMB_REPLACEMENT",
          "",
          0,
          -1,
          0,
          -3,
          -3,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    TYPE_3_LIMB_REPLACEMENT("TYPE_3_LIMB_REPLACEMENT",
          "",
          0,
          0,
          0,
          -2,
          -2,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    TYPE_4_LIMB_REPLACEMENT("TYPE_4_LIMB_REPLACEMENT",
          "",
          0,
          0,
          0,
          -1,
          -1,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    TYPE_5_LIMB_REPLACEMENT("TYPE_5_LIMB_REPLACEMENT",
          "",
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    TYPE_6_LIMB_REPLACEMENT("TYPE_6_LIMB_REPLACEMENT",
          "",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    TYPE_2_SENSORY_REPLACEMENT("TYPE_2_SENSORY_REPLACEMENT",
          "",
          -1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    TYPE_3_SENSORY_REPLACEMENT("TYPE_3_SENSORY_REPLACEMENT",
          "",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    TYPE_4_SENSORY_REPLACEMENT("TYPE_4_SENSORY_REPLACEMENT",
          "",
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    MYOMER_IMPLANT_ARM("MYOMER_IMPLANT_ARM",
          "",
          0,
          1,
          0,
          0,
          1,
          0,
          0,
          -1,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    TRIPLE_STRENGTH_MYOMER_IMPLANT_ARM("TRIPLE_STRENGTH_MYOMER_IMPLANT_ARM",
          "",
          0,
          1,
          1,
          0,
          1,
          0,
          0,
          -1,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    MYOMER_IMPLANT_HAND("MYOMER_IMPLANT_HAND",
          "",
          0,
          0,
          0,
          0,
          1,
          0,
          0,
          -1,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    MYOMER_IMPLANT_LEG("MYOMER_IMPLANT_LEG",
          "",
          0,
          1,
          0,
          1,
          0,
          0,
          0,
          -1,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    TRIPLE_STRENGTH_MYOMER_IMPLANT_LEG("TRIPLE_STRENGTH_MYOMER_IMPLANT_LEG",
          "",
          0,
          1,
          1,
          1,
          0,
          0,
          0,
          -1,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    BONE_REINFORCEMENT("BONE_REINFORCEMENT",
          "",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          false,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    LIVER_FILTRATION_IMPLANT("LIVER_FILTRATION_IMPLANT",
          "",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    TYPE_1_SURVIVAL_IMPLANT("TYPE_1_SURVIVAL_IMPLANT",
          "",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          1,
          0,
          0,
          0,
          0,
          0,
          0),
    TYPE_2_SURVIVAL_IMPLANT("TYPE_2_SURVIVAL_IMPLANT",
          "",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          2,
          0,
          0,
          0,
          0,
          0,
          0),
    TYPE_3_SURVIVAL_IMPLANT("TYPE_3_SURVIVAL_IMPLANT",
          "",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          3,
          0,
          0,
          0,
          0,
          0,
          0),
    EYESIGHT_ENHANCED("CYBERNETIC_EYE_TELESCOPE",
          "",
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    EYESIGHT_LASER("EYESIGHT_LASER",
          "",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0),
    EYESIGHT_MULTI("EYESIGHT_MULTI",
          "",
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          1,
          0,
          0,
          0,
          0,
          0),
    HEARING_ENHANCED("HEARING_ENHANCED",
          "",
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    CYBERNETIC_SPEECH_IMPLANT("CYBERNETIC_SPEECH_IMPLANT",
          "",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0),
    PHEROMONE_EFFUSER("PHEROMONE_EFFUSER",
          "",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          2,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    COSMETIC_BEAUTY_ENHANCEMENT("COSMETIC_BEAUTY_ENHANCEMENT",
          "",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          false,
          0,
          0,
          0,
          1,
          1,
          1,
          0,
          0),
    COSMETIC_HORROR_ENHANCEMENT("COSMETIC_HORROR_ENHANCEMENT",
          "",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          false,
          0,
          0,
          0,
          1,
          0,
          0,
          0,
          0),
    COSMETIC_ANIMAL_LIMB_PROSTHETIC("COSMETIC_ANIMAL_LIMB_PROSTHETIC",
          "",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1),
    STRESS("STRESS",
          "",
          0,
          -1,
          -1,
          -1,
          -1,
          -1,
          -1,
          -1,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    TRIPLE_CORE_PROCESSOR("TRIPLE_CORE_PROCESSOR",
          "",
          0,
          0,
          -1,
          0,
          0,
          5,
          0,
          -1,
          false,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    PAIN_SHUNT("PAIN_SHUNT",
          "",
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          false,
          5,
          0,
          0,
          0,
          0,
          0,
          0,
          0),
    PAIN_SHUNT_RECOVERY("PAIN_SHUNT_RECOVERY",
          "",
          0,
          0,
          0,
          -1,
          -1,
          0,
          0,
          0,
          false,
          5,
          0,
          0,
          0,
          0,
          0,
          0,
          0);

    private static final String RESOURCE_BUNDLE = "mekhq.resources.InjuryEffect";

    private final String lookupName;
    private final String textColor;
    private final int perceptionModifier;
    private final int strengthModifier;
    private final int bodyModifier;
    private final int reflexesModifier;
    private final int dexterityModifier;
    private final int intelligenceModifier;
    private final int willpowerModifier;
    private final int charismaModifier;
    private final int toughnessModifier;
    private final int survivalModifier;
    private final int gunneryModifier;
    private final int actingModifier;
    private final int negotiationModifier;
    private final int leadershipModifier;
    private final int interrogationModifier;
    private final int acrobaticsModifier;
    private final boolean inflictsPostScenarioInjury;

    InjuryEffect(String lookupName) {
        this.lookupName = lookupName;
        this.textColor = "";
        this.perceptionModifier = 0;
        this.strengthModifier = 0;
        this.bodyModifier = 0;
        this.reflexesModifier = 0;
        this.dexterityModifier = 0;
        this.intelligenceModifier = 0;
        this.willpowerModifier = 0;
        this.charismaModifier = 0;
        this.inflictsPostScenarioInjury = false;
        this.toughnessModifier = 0;
        this.survivalModifier = 0;
        this.gunneryModifier = 0;
        this.actingModifier = 0;
        this.negotiationModifier = 0;
        this.leadershipModifier = 0;
        this.interrogationModifier = 0;
        this.acrobaticsModifier = 0;
    }

    InjuryEffect(String lookupName, String textColor, int perceptionModifier, int strengthModifier, int bodyModifier,
          int reflexesModifier, int dexterityModifier, int intelligenceModifier, int willpowerModifier,
          int charismaModifier, boolean inflictsPostScenarioInjury, int toughnessModifier, int survivalModifier,
          int gunneryModifier, int actingModifier, int negotiationModifier, int leadershipModifier,
          int interrogationModifier, int acrobaticsModifier) {
        this.lookupName = lookupName;
        this.textColor = textColor;
        this.perceptionModifier = perceptionModifier;
        this.strengthModifier = strengthModifier;
        this.bodyModifier = bodyModifier;
        this.reflexesModifier = reflexesModifier;
        this.dexterityModifier = dexterityModifier;
        this.intelligenceModifier = intelligenceModifier;
        this.willpowerModifier = willpowerModifier;
        this.charismaModifier = charismaModifier;
        this.toughnessModifier = toughnessModifier;
        this.survivalModifier = survivalModifier;
        this.gunneryModifier = gunneryModifier;
        this.inflictsPostScenarioInjury = inflictsPostScenarioInjury;
        this.actingModifier = actingModifier;
        this.negotiationModifier = negotiationModifier;
        this.leadershipModifier = leadershipModifier;
        this.interrogationModifier = interrogationModifier;
        this.acrobaticsModifier = acrobaticsModifier;
    }

    public int getPerceptionModifier() {
        return perceptionModifier;
    }

    public int getStrengthModifier() {
        return strengthModifier;
    }

    public int getBodyModifier() {
        return bodyModifier;
    }

    public int getReflexesModifier() {
        return reflexesModifier;
    }

    public int getDexterityModifier() {
        return dexterityModifier;
    }

    public int getIntelligenceModifier() {
        return intelligenceModifier;
    }

    public int getWillpowerModifier() {
        return willpowerModifier;
    }

    public int getCharismaModifier() {
        return charismaModifier;
    }

    public int getToughnessModifier() {
        return toughnessModifier;
    }

    public int getSurvivalModifier() {
        return survivalModifier;
    }

    public int getGunneryModifier() {
        return gunneryModifier;
    }

    public int getActingModifier() {
        return actingModifier;
    }

    public int getNegotiationModifier() {
        return negotiationModifier;
    }

    public int getLeadershipModifier() {
        return leadershipModifier;
    }

    public int getInterrogationModifier() {
        return interrogationModifier;
    }

    public int getAcrobaticsModifier() {
        return acrobaticsModifier;
    }

    public boolean isInflictsPostScenarioInjury() {
        return inflictsPostScenarioInjury;
    }

    public String getTextColor() {
        return textColor;
    }

    @Override
    public String toString() {
        return getTextAt(RESOURCE_BUNDLE, "InjuryEffect." + lookupName + ".name");
    }

    /**
     * Builds a localized tooltip summarizing key information about all active injury effects.
     *
     * <p><b>Note:</b> For consistency, the order shown in the tooltip is meant to mirror that of
     * {@link ProstheticType#getTooltip(Faction, int, boolean)}.</p>
     *
     * @param injuryEffects A list of currently active injury effects
     *
     * @return a formatted tooltip string suitable for UI display
     *
     * @author Illiani
     * @since 0.50.10
     */
    public static String getTooltip(List<InjuryEffect> injuryEffects) {
        // Map attributes to their aggregated modifiers
        Map<SkillAttribute, Integer> attributeTotals = new EnumMap<>(SkillAttribute.class);
        int gunneryTotal = 0;
        int perceptionTotal = 0;
        int toughnessTotal = 0;
        int survivalTotal = 0;
        int actingTotal = 0;
        int negotiationTotal = 0;
        int leadershipTotal = 0;
        int interrogationTotal = 0;
        int acrobaticsTotal = 0;
        int postScenarioInjuries = 0;

        // Aggregate modifiers
        for (InjuryEffect effect : injuryEffects) {
            gunneryTotal += effect.getGunneryModifier();
            perceptionTotal += effect.getPerceptionModifier();
            toughnessTotal += effect.getToughnessModifier();
            survivalTotal += effect.getSurvivalModifier();
            actingTotal += effect.getActingModifier();
            negotiationTotal += effect.getNegotiationModifier();
            leadershipTotal += effect.getLeadershipModifier();
            interrogationTotal += effect.getInterrogationModifier();
            acrobaticsTotal += effect.getAcrobaticsModifier();
            addToMap(attributeTotals, SkillAttribute.STRENGTH, effect.getStrengthModifier());
            addToMap(attributeTotals, SkillAttribute.BODY, effect.getBodyModifier());
            addToMap(attributeTotals, SkillAttribute.REFLEXES, effect.getReflexesModifier());
            addToMap(attributeTotals, SkillAttribute.DEXTERITY, effect.getDexterityModifier());
            addToMap(attributeTotals, SkillAttribute.INTELLIGENCE, effect.getIntelligenceModifier());
            addToMap(attributeTotals, SkillAttribute.WILLPOWER, effect.getWillpowerModifier());
            addToMap(attributeTotals, SkillAttribute.CHARISMA, effect.getCharismaModifier());

            if (effect.isInflictsPostScenarioInjury()) {
                postScenarioInjuries++;
            }
        }

        // Build tooltip
        List<String> tooltipPortion = new ArrayList<>();

        // 1) Misc
        if (toughnessTotal != 0) {
            tooltipPortion.add(getFormattedTextAt(RESOURCE_BUNDLE,
                  "InjuryEffect.tooltip.toughness", toughnessTotal));
        }

        // 2) Skills
        if (gunneryTotal != 0) {
            tooltipPortion.add(getFormattedTextAt(RESOURCE_BUNDLE,
                  "InjuryEffect.tooltip.gunnery", gunneryTotal));
        }

        if (leadershipTotal != 0) {
            tooltipPortion.add(getFormattedTextAt(RESOURCE_BUNDLE,
                  "InjuryEffect.tooltip.leadership", leadershipTotal));
        }

        if (negotiationTotal != 0) {
            tooltipPortion.add(getFormattedTextAt(RESOURCE_BUNDLE,
                  "InjuryEffect.tooltip.negotiation", negotiationTotal));
        }

        if (perceptionTotal != 0) {
            tooltipPortion.add(getFormattedTextAt(RESOURCE_BUNDLE,
                  "InjuryEffect.tooltip.perception", perceptionTotal));
        }

        if (survivalTotal != 0) {
            tooltipPortion.add(getFormattedTextAt(RESOURCE_BUNDLE,
                  "InjuryEffect.tooltip.survival", survivalTotal));
        }

        if (interrogationTotal != 0) {
            tooltipPortion.add(getFormattedTextAt(RESOURCE_BUNDLE,
                  "InjuryEffect.tooltip.interrogation", interrogationTotal));
        }

        if (actingTotal != 0) {
            tooltipPortion.add(getFormattedTextAt(RESOURCE_BUNDLE,
                  "InjuryEffect.tooltip.acting", actingTotal));
        }

        if (acrobaticsTotal != 0) {
            tooltipPortion.add(getFormattedTextAt(RESOURCE_BUNDLE,
                  "InjuryEffect.tooltip.acrobatics", acrobaticsTotal));
        }

        // 3) Attributes
        for (SkillAttribute attribute : SkillAttribute.values()) {
            int modifier = attributeTotals.getOrDefault(attribute, 0);
            if (modifier != 0) {
                tooltipPortion.add(getFormattedTextAt(RESOURCE_BUNDLE,
                      "InjuryEffect.tooltip.attribute", modifier, attribute.getLabel()));
            }
        }

        // 4) Critical Effects
        if (postScenarioInjuries > 0) {
            tooltipPortion.add(getFormattedTextAt(RESOURCE_BUNDLE,
                  "InjuryEffect.tooltip.inflictsHit", postScenarioInjuries));
        }

        return String.join(" ", tooltipPortion);
    }

    private static void addToMap(Map<SkillAttribute, Integer> map, SkillAttribute key, int value) {
        map.merge(key, value, Integer::sum);
    }

    public static String getEffectsLabel(List<InjuryEffect> injuryEffects) {
        // Count occurrences of each effect
        Map<InjuryEffect, Long> effectCounts = injuryEffects.stream()
                                                     .collect(Collectors.groupingBy(
                                                           Function.identity(),
                                                           LinkedHashMap::new,
                                                           Collectors.counting()
                                                     ));

        // Format each effect with color and count
        StringBuilder effects = new StringBuilder();
        for (Map.Entry<InjuryEffect, Long> entry : effectCounts.entrySet()) {
            if (!effects.isEmpty()) {
                effects.append(", ");
            }
            effects.append(formatEffect(entry.getKey(), entry.getValue()));
        }

        return "<html>" + effects + "</html>";
    }

    private static String formatEffect(InjuryEffect effect, long count) {
        String color = effect.getTextColor();
        String openSpan = color.isBlank() ? "" : spanOpeningWithCustomColor(color);
        String closeSpace = color.isBlank() ? "" : CLOSING_SPAN_TAG;
        String effectName = openSpan + effect + closeSpace;
        return count > 1 ? effectName + " (x" + count + ")" : effectName;
    }
}
