/*
 * Copyright (C) 2026 The MegaMek Team. All Rights Reserved.
 *
 * This file is part of MekHQ.
 *
 * MekHQ is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License (GPL),
 * version 3 or (at your option) any later version,
 * as published by the Free Software Foundation.
 *
 * MekHQ is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * A copy of the GPL should have been included with this project;
 * if not, see <https://www.gnu.org/licenses/>.
 *
 * NOTICE: The MekHQ organization is a non-profit group of volunteers
 * creating free software for the BattleTech community.
 *
 * MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
 * of The Topps Company, Inc. All Rights Reserved.
 *
 * Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
 * InMediaRes Productions, LLC.
 *
 * MechWarrior Copyright Microsoft Corporation. MekHQ was created under
 * Microsoft's "Game Content Usage Rules"
 * <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
 * affiliated with Microsoft.
 */
package mekhq.campaign.universe.commandGeneration;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.EnumSet;
import megamek.common.enums.SkillLevel;
import mekhq.campaign.personnel.enums.PersonnelRole;
import mekhq.campaign.universe.enums.TechAssignmentSortFactor;
import org.junit.jupiter.api.Test;

/**
 * Constructor-default coverage for {@link CommandGenerationOptions}. The defaults must match the
 * legacy {@code RULESET_BASED} configuration of the deprecated {@code CompanyGenerationOptions}
 * this class replaced, so a fresh Command Designer run generates the same force it always did.
 */
class CommandGenerationOptionsTest {

    private static final PersonnelRole[] SUPPORT_ROLES = {
          PersonnelRole.MEK_TECH, PersonnelRole.MECHANIC, PersonnelRole.AERO_TEK, PersonnelRole.BA_TECH,
          PersonnelRole.DOCTOR, PersonnelRole.ADMINISTRATOR
    };

    @Test
    void constructor_seedsCoveragePercentsAtOneHundred_forEverySupportRole() {
        CommandGenerationOptions options = new CommandGenerationOptions();

        assertNotNull(options.getSupportPersonnelCoveragePercents());
        for (PersonnelRole role : SUPPORT_ROLES) {
            assertEquals(100, options.getSupportPersonnelCoveragePercents().get(role),
                  "Default coverage for " + role.name() + " should be 100");
        }
    }

    @Test
    void constructor_defaultsSkillLevelsToRandom_forEverySupportRole() {
        CommandGenerationOptions options = new CommandGenerationOptions();

        assertNotNull(options.getSupportPersonnelSkillLevels());
        for (PersonnelRole role : SUPPORT_ROLES) {
            // null = the "Random" picker option: each generated person rolls their own level.
            assertNull(options.getSupportPersonnelSkillLevels().get(role),
                  "Default skill level for " + role.name() + " should be Random (null)");
        }
    }

    @Test
    void constructor_assistantDefaults_matchLegacyPoolAssistantsBehavior() {
        CommandGenerationOptions options = new CommandGenerationOptions();

        assertTrue(options.isGenerateAstechs(), "Astechs generated by default");
        assertFalse(options.isAstechsAsPersonnel(), "Pool mode by default");
        assertNull(options.getAstechSkillLevel(), "Astech skill defaults to Random");

        assertTrue(options.isGenerateMedics());
        assertFalse(options.isMedicsAsPersonnel());
        assertNull(options.getMedicSkillLevel(), "Medic skill defaults to Random");
    }

    @Test
    void constructor_pipelineDefaults_matchLegacyRulesetBasedConfiguration() {
        CommandGenerationOptions options = new CommandGenerationOptions();

        // Tech-to-unit assignment grid: officers first, then heaviest, then best pilot.
        assertTrue(options.isAssignTechsToUnits());
        assertEquals(TechAssignmentSortFactor.PILOT_RANK, options.getTechAssignmentPrimarySort());
        assertTrue(options.isTechAssignmentPrimaryDescending());
        assertEquals(TechAssignmentSortFactor.UNIT_WEIGHT, options.getTechAssignmentSecondarySort());
        assertTrue(options.isTechAssignmentSecondaryDescending());
        assertEquals(TechAssignmentSortFactor.PILOT_SKILL, options.getTechAssignmentTertiarySort());
        assertTrue(options.isTechAssignmentTertiaryDescending());

        // Rank assignment and personnel flags.
        assertTrue(options.isAutomaticallyAssignRanks());
        assertTrue(options.isUseSpecifiedFactionToAssignRanks());
        assertTrue(options.isAssignCompanyCommanderFlag());
        assertTrue(options.isAssignMekWarriorsCallSigns());
        assertTrue(options.isAssignFounderFlag());

        // Formation icons.
        assertTrue(options.isGenerateFormationIcons());
        assertFalse(options.isUseSpecifiedFactionToGenerateFormationIcons());
        assertTrue(options.isGenerateOriginNodeFormationIcon());
        assertFalse(options.isUseOriginNodeFormationIconLogo());

        // Finances: the command is granted free, with working capital defaulting to 10% of the
        // generated units' purchase cost.
        assertTrue(options.isProcessFinances());
        assertEquals(10, options.getStartingCashPercent());
    }

    @Test
    void forceDescriptorSnapshot_isLazilyInitialized_andNeverNull() {
        CommandGenerationOptions options = new CommandGenerationOptions();

        assertNotNull(options.getForceDescriptorSnapshot(), "Snapshot must lazy-initialize");
        assertSame(options.getForceDescriptorSnapshot(), options.getForceDescriptorSnapshot(),
              "Repeated access must return the same snapshot instance");
    }
    /** The dialog compares the tabs against the settings captured at Generate, so equality must be by value. */
    @Test
    void twoFreshOptionsAreEqual() {
        assertEquals(new CommandGenerationOptions(), new CommandGenerationOptions());
        assertEquals(new CommandGenerationOptions().hashCode(), new CommandGenerationOptions().hashCode());
    }

    @Test
    void aChangedSettingBreaksEquality() {
        CommandGenerationOptions options = new CommandGenerationOptions();
        CommandGenerationOptions changed = new CommandGenerationOptions();
        changed.setTemporaryCrewRoles(EnumSet.of(TemporaryCrewRole.INFANTRY));
        assertNotEquals(options, changed, "a temporary-crew choice is part of the settings");

        changed = new CommandGenerationOptions();
        changed.getSupportPersonnelCoveragePercents().put(PersonnelRole.DOCTOR, 200);
        assertNotEquals(options, changed, "a coverage percentage is part of the settings");

        changed = new CommandGenerationOptions();
        changed.getForceDescriptorSnapshot().setYear(3025);
        assertNotEquals(options, changed, "the force description is part of the settings");
    }
}
