/*
 * AlertPopup.java
 *
 * Created on Jan 6, 2010, 10:46:02 PM
 */

package mekhq;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author natit
 */
public class PopupValueChoiceDialog extends javax.swing.JDialog {

    /**
	 * This was originally set up as a text entry dialog, but there is 
	 * really no reason to use it instead of the pre-fab inputdialog that
	 * comes with java and it was actually causing problems because it uses
	 * a textpane instead of a textfield. Since it is currently only called by 
	 * the set xp command in MekHQView, I am going to refactor it into a 
	 * numeric value setter using a spinner.
	 */
	private static final long serialVersionUID = 8376874926997734492L;
	/** Creates new form */
    public PopupValueChoiceDialog(java.awt.Frame parent, boolean modal, String title, int current, int min, int max) {
        super(parent, modal);
        model = new javax.swing.SpinnerNumberModel(current, min, max, 1);
        label = new javax.swing.JLabel(title);
        initComponents();      
        setLocationRelativeTo(parent);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        btnDone = new javax.swing.JButton();
        value = new javax.swing.JSpinner(model);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(mekhq.MekHQApp.class).getContext().getResourceMap(PopupValueChoiceDialog.class);
        btnDone.setText(resourceMap.getString("btnDone.text")); // NOI18N
        btnDone.setName("btnDone"); // NOI18N
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        value.setName("value"); // NOI18N
        label.setName("label"); // NOI18N

        getContentPane().setLayout(new GridBagLayout());
        
        GridBagConstraints c= new GridBagConstraints();
        c.gridx = 0;
        c.fill = java.awt.GridBagConstraints.BOTH;
		c.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(label,c);
        c.gridx = 1;
        getContentPane().add(value, c);
        c.gridx = 0;
        c.gridy = 1;
        c.gridwidth = 2;
		c.anchor = java.awt.GridBagConstraints.CENTER;
        getContentPane().add(btnDone, c);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        this.setVisible(false);
}//GEN-LAST:event_btnDoneActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PopupValueChoiceDialog dialog = new PopupValueChoiceDialog(new javax.swing.JFrame(), true, "Label", 0, 0, 1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public int getValue() {
    	return (Integer)value.getValue();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDone;
    private javax.swing.JLabel label;
    private javax.swing.JSpinner value;
    private javax.swing.SpinnerNumberModel model;
    // End of variables declaration//GEN-END:variables

}
