/*
 * CamoChoiceDialog.java
 *
 * Created on October 1, 2009, 3:10 PM
 */

package mekhq;

import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.Iterator;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JTable;
import javax.swing.event.MouseInputAdapter;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableCellRenderer;

import megamek.client.ui.AWT.util.ImageFileFactory;
import megamek.common.Pilot;
import megamek.common.util.DirectoryItems;

/**
 *
 * @author  Jay Lawson <jaylawson39 at yahoo.com>
 */
public class PortraitChoiceDialog extends javax.swing.JDialog {

     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * The categorized camo patterns.
     */
    private DirectoryItems portraits;
    private PortraitTableModel portraitModel = new PortraitTableModel();
    private String category;
    private String filename;
    private PortraitTableMouseAdapter portraitMouseAdapter;


    /** Creates new form CamoChoiceDialog */
    public PortraitChoiceDialog(java.awt.Frame parent, boolean modal, String category, String file) {
        super(parent, modal);
        this.category = category;
        filename = file;
        portraitMouseAdapter = new PortraitTableMouseAdapter();
        // Parse the camo directory.
        try {
            portraits = new DirectoryItems(new File("data/images/portraits"), "", //$NON-NLS-1$ //$NON-NLS-2$
                    ImageFileFactory.getInstance());
        } catch (Exception e) {
            portraits = null;
        }
        initComponents();
        fillTable((String) comboCategories.getSelectedItem());
        int rowIndex = 0;
        for(int i = 0; i < portraitModel.getRowCount(); i++) {
            if(((String) portraitModel.getValueAt(i, 0)).equals(filename)) {
                rowIndex = i;
                break;
            }
        }
        tablePortrait.setRowSelectionInterval(rowIndex, rowIndex);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        tablePortrait = new javax.swing.JTable();
        comboCategories = new javax.swing.JComboBox();
        btnSelect = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tablePortrait.setModel(portraitModel);
        tablePortrait.setName("tablePortrait"); // NOI18N
        tablePortrait.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablePortrait.setRowHeight(76);
        tablePortrait.getColumnModel().getColumn(0).setCellRenderer(portraitModel.getRenderer());
        tablePortrait.addMouseListener(portraitMouseAdapter);
        jScrollPane1.setViewportView(tablePortrait);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        DefaultComboBoxModel categoryModel = new DefaultComboBoxModel();
        String match = null;
        categoryModel.addElement(Pilot.ROOT_PORTRAIT);
        if (portraits != null) {
            Iterator<String> names = portraits.getCategoryNames();
            while (names.hasNext()) {
                String name = names.next();
                if (!"".equals(name)) { //$NON-NLS-1$
                    categoryModel.addElement(name);
                    if(category.equals(name)) {
                        match = name;
                    }
                }
            }
        }
        if(null != match) {
            categoryModel.setSelectedItem(match);
        } else {
            categoryModel.setSelectedItem(Pilot.ROOT_PORTRAIT);
        }
        comboCategories.setModel(categoryModel);
        comboCategories.setName("comboCategories"); // NOI18N
        comboCategories.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCategoriesItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(comboCategories, gridBagConstraints);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(mekhq.MekHQApp.class).getContext().getResourceMap(PortraitChoiceDialog.class);
        btnSelect.setText(resourceMap.getString("btnSelect.text")); // NOI18N
        btnSelect.setName("btnSelect"); // NOI18N
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.5;
        getContentPane().add(btnSelect, gridBagConstraints);

        btnCancel.setText(resourceMap.getString("btnCancel.text")); // NOI18N
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.5;
        getContentPane().add(btnCancel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    setVisible(false);
}//GEN-LAST:event_btnCancelActionPerformed

private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
    category = portraitModel.getCategory();
    if(tablePortrait.getSelectedRow() != -1) {
        filename = (String) portraitModel.getValueAt(tablePortrait.getSelectedRow(), 0);
    } else {
        filename = Pilot.PORTRAIT_NONE;
    }
    setVisible(false);
}//GEN-LAST:event_btnSelectActionPerformed

private void comboCategoriesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCategoriesItemStateChanged
    if (evt.getStateChange() == ItemEvent.SELECTED) {
        fillTable((String) evt.getItem());
    }
}//GEN-LAST:event_comboCategoriesItemStateChanged

    public String getCategory() {
        return category;
    }

    public String getFileName() {
        return filename;
    }

     private void fillTable(String category) {
        portraitModel.reset();
        portraitModel.setCategory(category);
        // Translate the "root camo" category name.
        Iterator<String> portraitNames;
        if (Pilot.ROOT_PORTRAIT.equals(category)) {
            portraitModel.addPortrait(Pilot.PORTRAIT_NONE);
            portraitNames = portraits.getItemNames(""); //$NON-NLS-1$
        } else {
            portraitNames = portraits.getItemNames(category);
        }

        // Get the camo names for this category.
        while (portraitNames.hasNext()) {
                portraitModel.addPortrait(portraitNames.next());
        }
        if(portraitModel.getRowCount() > 0) {
            tablePortrait.setRowSelectionInterval(0, 0);
        }
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PortraitChoiceDialog dialog = new PortraitChoiceDialog(new javax.swing.JFrame(), true, Pilot.ROOT_PORTRAIT, Pilot.PORTRAIT_NONE);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

     /**
        * A table model for displaying camos
     */
    public class PortraitTableModel extends AbstractTableModel {

        /**
		 * 
		 */
		private static final long serialVersionUID = 1L;
		private String[] columnNames;
        private String category;
        private ArrayList<String> names;
        private ArrayList<Image> images;

        public PortraitTableModel() {
            columnNames = new String[] {"Portraits"};
            category = Pilot.ROOT_PORTRAIT;
            names = new ArrayList<String>();
            images = new ArrayList<Image>();
        }

        public int getRowCount() {
            return names.size();
        }

        public int getColumnCount() {
            return 1;
        }

        public void reset() {
            category = Pilot.ROOT_PORTRAIT;
            names = new ArrayList<String>();
            images = new ArrayList<Image>();
        }

        @Override
        public String getColumnName(int column) {
            return columnNames[column];
        }

        public Object getValueAt(int row, int col) {
            return names.get(row);
        }

        public Object getImageAt(int row) {
            return images.get(row);
        }

        public void setCategory(String c) {
            category = c;
        }

        public String getCategory() {
            return category;
        }

        public void addPortrait(String name) {
            names.add(name);
            fireTableDataChanged();
        }

        @Override
        public Class<? extends Object> getColumnClass(int c) {
            return getValueAt(0, c).getClass();
        }

        @Override
        public boolean isCellEditable(int row, int col) {
            return false;
        }

        public PortraitTableModel.Renderer getRenderer() {
            return new PortraitTableModel.Renderer();
        }


        public class Renderer extends PortraitPanel implements TableCellRenderer {
			private static final long serialVersionUID = -6025788865509594987L;

			public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = this;
                setOpaque(true);
                String name = getValueAt(row, column).toString();
                setText(getValueAt(row, column).toString());
                setImage(category, name);
                if(isSelected) {
                    setBackground(new Color(220,220,220));
                } else {
                    setBackground(Color.WHITE);
                }

                return c;
            }
       }
    }

    public class PortraitTableMouseAdapter extends MouseInputAdapter {

        @Override
        public void mouseClicked(MouseEvent e) {

            if (e.getClickCount() == 2) {
                int row = tablePortrait.rowAtPoint(e.getPoint());
                if(row < portraitModel.getRowCount()) {
                    category = portraitModel.getCategory();
                    filename = (String) portraitModel.getValueAt(row, 0);
                    setVisible(false);
                }
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSelect;
    private javax.swing.JComboBox comboCategories;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePortrait;
    // End of variables declaration//GEN-END:variables

}
