/*
 * StartUpDialog.java
 *
 * Created on Jan 6, 2010, 10:46:02 PM
 */

package mekhq;

import java.awt.Frame;

import org.jdesktop.application.SingleFrameApplication;

import megamek.common.MechSummaryCache;
import mekhq.campaign.Campaign;
import mekhq.campaign.Planets;

/**
 *
 * @author Jay
 */
public class StartUpDialog extends javax.swing.JDialog {

	
	private static final long serialVersionUID = 8376874926997734492L;
	SingleFrameApplication app;
	/** Creates new form */
    public StartUpDialog(SingleFrameApplication app) {
        super(app.getMainFrame(), true);
        this.app = app;
        initComponents();      
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {


        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        java.awt.GridBagConstraints gridBagConstraints;
        getContentPane().setLayout(new java.awt.GridBagLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(mekhq.MekHQApp.class).getContext().getResourceMap(StartUpDialog.class);
        
        btnNewGame = new javax.swing.JButton("Start a New Game");
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	setVisible(false);
            	loadNewCampaign();  	
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(btnNewGame, gridBagConstraints);
     
        pack();
    }

    private void loadNewCampaign() {
    	DataLoadingDialog dataLoadingDialog = new DataLoadingDialog(app);   	
    	dataLoadingDialog.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewGame;
    // End of variables declaration//GEN-END:variables

}
