package mekhq.campaign.personnel;

public enum AwardNames {
    //armedForces,
    //bronzeStar,
    clanInvasionCampaign,
    //combatAchievement,
    //combatAction,
    combatCommendation,
    //combatCross,
    //combatUnitCommendation,
    distinguishedService,
    expeditionary,
    //fedcomCivilWarCampaign,
    fourthSuccessionWarCampaign,
    //galacticService,
    //galacticServiceDeployment,
    //galacticWarOnPirating,
    //goodConduct,
    //houseDefence,
    //houseDistinguishedService,
    //houseMeritouriousService,
    //houseUnitCitation,
    humanitarianService,
    //legionOfMerit,
    //meritouriousService,
    //meritousUnitCommendation,
    peripheryExpeditionary,
    //pow,
    //purpleHeart,
    //silverStar,
    taskForceSerpentCampaign,
    thirdSuccessionWarCampaign,
    warOf3039Campaign
}
