/*
 * Copyright (C) 2025 The MegaMek Team. All Rights Reserved.
 *
 * This file is part of MekHQ.
 *
 * MekHQ is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License (GPL),
 * version 3 or (at your option) any later version,
 * as published by the Free Software Foundation.
 *
 * MekHQ is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * A copy of the GPL should have been included with this project;
 * if not, see <https://www.gnu.org/licenses/>.
 *
 * NOTICE: The MegaMek organization is a non-profit group of volunteers
 * creating free software for the BattleTech community.
 *
 * MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
 * of The Topps Company, Inc. All Rights Reserved.
 *
 * Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
 * InMediaRes Productions, LLC.
 *
 * MechWarrior Copyright Microsoft Corporation. MekHQ was created under
 * Microsoft's "Game Content Usage Rules"
 * <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
 * affiliated with Microsoft.
 */
package mekhq.campaign.enums;

import static mekhq.utilities.MHQInternationalization.getTextAt;

import megamek.common.annotations.Nullable;

/**
 * Represents the various log categories available in the campaign interface.
 *
 * @author Illiani
 * @since 0.50.10
 */
public enum DailyReportType {
    /**
     * General-purpose logs covering day-to-day campaign events and status updates.
     */
    GENERAL("GENERAL", 0),

    /**
     * Logs related to combat activity, including battle resolutions, scenario results, and other wartime operational
     * records.
     */
    BATTLE("BATTLE", 1),

    /**
     * Logs detailing personnel activity such as hiring, promotions, injuries, training progress, and individual
     * character events.
     */
    PERSONNEL("PERSONNEL", 2),

    /**
     * Logs tracking medical events, including injuries, treatments, recovery updates, and outcomes from the advanced
     * medical system.
     */
    MEDICAL("MEDICAL", 3),

    /**
     * Logs related to purchasing, selling, and acquiring equipment, units, supplies, and other assets.
     */
    FINANCES("FINANCES", 4),

    /**
     * Logs related to purchasing, selling, and acquiring equipment, units, supplies, and other assets.
     */
    ACQUISITIONS("ACQUISITIONS", 5),

    /**
     * Logs reflecting technical and maintenance activity, such as repairs, refits, malfunction reports, and engineering
     * operations.
     */
    TECHNICAL("TECHNICAL", 6),

    /**
     * Logs generated by skill checks performed throughout the campaign, including training rolls, aptitude tests, and
     * scenario-related skill usage.
     */
    SKILL_CHECKS("SKILL_CHECKS", 7);

    private static final String RESOURCE_BUNDLE = "mekhq.resources.DailyReportType";

    private final String lookupName;
    private final String iconString;
    private final String tooltip;
    private final int tabIndex;

    DailyReportType(String lookupName, int tabIndex) {
        this.lookupName = lookupName;
        this.iconString = generateIconString();
        this.tooltip = generateTooltip();
        this.tabIndex = tabIndex;
    }

    private String generateIconString() {
        return getTextAt(RESOURCE_BUNDLE, "DailyReportType." + lookupName + ".iconString");
    }

    private String generateTooltip() {
        return getTextAt(RESOURCE_BUNDLE, "DailyReportType." + lookupName + ".tooltip");
    }

    public String getTooltip() {
        return tooltip;
    }

    public String getIconString() {
        return iconString;
    }

    public int getTabIndex() {
        return tabIndex;
    }

    public static @Nullable DailyReportType getTypeFromIndex(int tabIndex) {
        for (DailyReportType type : DailyReportType.values()) {
            if (tabIndex == type.getTabIndex()) {
                return type;
            }
        }

        return null;
    }
}

