/*
 * Copyright (C) 2025 The MegaMek Team. All Rights Reserved.
 *
 * This file is part of MekHQ.
 *
 * MekHQ is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License (GPL),
 * version 3 or (at your option) any later version,
 * as published by the Free Software Foundation.
 *
 * MekHQ is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * A copy of the GPL should have been included with this project;
 * if not, see <https://www.gnu.org/licenses/>.
 *
 * NOTICE: The MegaMek organization is a non-profit group of volunteers
 * creating free software for the BattleTech community.
 *
 * MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
 * of The Topps Company, Inc. All Rights Reserved.
 *
 * Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
 * InMediaRes Productions, LLC.
 *
 * MechWarrior Copyright Microsoft Corporation. MekHQ was created under
 * Microsoft's "Game Content Usage Rules"
 * <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
 * affiliated with Microsoft.
 */
package mekhq.campaign.personnel.skills;

import java.util.List;

import mekhq.campaign.personnel.Person;
import mekhq.campaign.personnel.PersonnelOptions;
import mekhq.campaign.personnel.medical.advancedMedicalAlternate.InjuryEffect;

/**
 * Encapsulates all data needed to calculate skill modifiers for a person.
 *
 * <p>This record aggregates various factors that affect skill checks and task resolution: This is typically
 * generated by {@link Person#getSkillModifierData()} or its variants, and passed to skill resolution methods.</p>
 *
 * <p><b>Note:</b> For Unit Tests you can usually get away with {@code TestSkillModifierData#createDefault()}</p>
 *
 * @param characterOptions   the person's options and special traits
 * @param attributes         the person's physical and mental attributes
 * @param adjustedReputation the calculated reputation modifier (0 if not applicable)
 * @param injuryEffects      a list of injury effects currently affecting the character
 * @param age                the age of the character, in years
 *
 * @author Illiani
 * @since 0.50.10
 */
public record SkillModifierData(PersonnelOptions characterOptions, Attributes attributes, int adjustedReputation,
      List<InjuryEffect> injuryEffects, int age) {
    /**
     * Special age value indicating that aging effects should be ignored.
     *
     * <p>When a character's age is set to {@code IGNORE_AGE}, all systems that compute age-based modifiers—such as
     * attribute adjustments or skill penalties—should treat the character as unaffected by aging. This allows campaigns
     * or characters to disable aging entirely without altering the underlying age mechanics elsewhere.</p>
     *
     * <p>The value {@code -1} is used as a sentinel and does not correspond to any valid chronological age.</p>
     */
    public static int IGNORE_AGE = -1;
}
